### ISSUE TITLE
Can't build standalone app after upgrade to sdk 33

### ISSUE THREAD

**Issue by dawidczech355a** [expo/turtle#112]
Hi, after upgrade to Expo SDK 33, travis CI can't build standalone apps for android and iOS, always crash on this line: 
- $ travis_wait 60 ./ci/build-android.sh

and given logs: 

Failed to setup environment for android builds
  err: Error: yarn exited with non-zero code: 1
      at ChildProcess.completionListener (/home/travis/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:317:30)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:915:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
      ...
      at spawnAsync (/home/travis/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (/@expo/xdl@55.0.7/src/detach/ExponentTools.js:126:21)
      at _installNodeModules (/home/travis/.config/yarn/global/node_modules/turtle-cli/src/bin/setup/android/index.ts:91:23)
      at <anonymous>
  platform: "android"

similar for the iOS:

wrong version of fastlane installed
  err: Error: Your fastlane on version 2.98.0. Please upgrade it to at least 2.99.0.
      at versionCheckFn (/Users/travis/.config/yarn/global/node_modules/turtle-cli/src/bin/setup/ios.ts:32:15)
      at <anonymous>
  platform: "ios"
  buildPhase: "setting up environment"

Failed to setup environment for ios builds
  err: Error: Tools required to perform standalone app build are missing. Please install them.
      at Object.ensureToolsAreInstalled (/Users/travis/.config/yarn/global/node_modules/turtle-cli/src/bin/setup/utils/toolsDetector.ts:44:11)
      at <anonymous>
  platform: "ios"

![Zrzut ekranu z 2019-07-09 14-35-23](https://user-images.githubusercontent.com/44273301/60888386-f7376280-a256-11e9-96a5-63fa0fc7e33a.png)

Every build finish with this errors.

If anyone had similar issue, please take me some advice.

**Comment by dsokal** [comment]
Closed due to inactivity, feel free to open another ticket if the problem persists.
