### ISSUE TITLE
Better output or verbose option

### ISSUE THREAD

**Issue by bodolsog** [expo/turtle#133]
#### Motivation Behind Feature
Sometimes setup (i.e. `turtle setup:android`) ends with unknown error from `@expo/spawn-async`

```
Aug 21 08:40:48 turtle[161] ERROR: Failed to build standalone app
  err: Error: yarn exited with non-zero code: 127
      at ChildProcess.completionListener (/usr/local/share/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:286:20)
      at ChildProcess.emit (events.js:198:13)
      at ChildProcess.EventEmitter.emit (domain.js:448:20)
      at maybeClose (internal/child_process.js:982:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
      ...
      at spawnAsync (/usr/local/share/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (/@expo/xdl@56.1.4-rc.0/src/detach/ExponentTools.ts:131:19)
      at _installNodeModules (/usr/local/share/.config/yarn/global/node_modules/turtle-cli/src/bin/setup/android/index.ts:91:23)
  platform: "android"
```

Where real issue was (in my case) missing `rsync` package. I got it trying manually install packages from `.turtle/workingdir/android/sdk34/`. I lost a lot of time trying to fix java jdk dependency as in other issues described.

#### Feature Description
Option for printing output from subcommands would be really helpful for a lot of possible future problems.

#### Alternatives or Workarounds
From current infos:
```
Aug 21 08:40:48 turtle[161] INFO:  Directory: /root/.turtle/workingdir/android/sdk34/packages/expo
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Aug 21 08:40:48 turtle[161] INFO:  Output:
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Aug 21 08:40:48 turtle[161] INFO:  info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Aug 21 08:40:48 turtle[161] INFO:  error Command failed with exit code 127.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Aug 21 08:40:48 turtle[161] INFO:  info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Aug 21 08:40:48 turtle[161] ERROR: Failed to build standalone app
  err: Error: yarn exited with non-zero code: 127
      at ChildProcess.completionListener (/usr/local/share/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:286:20)
      at ChildProcess.emit (events.js:198:13)
      at ChildProcess.EventEmitter.emit (domain.js:448:20)
      at maybeClose (internal/child_process.js:982:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
      ...
      at spawnAsync (/usr/local/share/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (/@expo/xdl@56.1.4-rc.0/src/detach/ExponentTools.ts:131:19)
      at _installNodeModules (/usr/local/share/.config/yarn/global/node_modules/turtle-cli/src/bin/setup/android/index.ts:91:23)
  platform: "android"
```

Navigate to directories where is something executed and try to do it manually, then check the output. Unfortunately not always is clear what is executed, I got a hint, because there was yarn executed and raised an error in next info outputs.

**Comment by bodolsog** [comment]
Some related issues which was hard to debug: 
- https://github.com/expo/turtle/issues/45
- https://github.com/expo/turtle/issues/64
- https://forums.expo.io/t/error-building-app-locally-using-turtle-cli/18748

**Comment by brayanL** [comment]
I followed [#64](https://github.com/expo/turtle/issues/64) and it throws the same error, is not clear, how to know what is the exact error?

```
Nov 12 13:56:37 turtle[3676] ERROR: Failed to setup environment for android builds
  err: Error: yarn exited with non-zero code: 1
      at ChildProcess.completionListener (/Users/distiller/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:273:13)
      at ChildProcess.emit (events.js:182:13)
      at ChildProcess.EventEmitter.emit (domain.js:441:20)
      at maybeClose (internal/child_process.js:962:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
      ...
      at spawnAsync (/Users/distiller/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (/@expo/xdl@56.2.2-alpha.2/src/detach/ExponentTools.ts:131:19)
      at _installNodeModules (/Users/distiller/.config/yarn/global/node_modules/turtle-cli/src/bin/setup/android/index.ts:103:23)
  platform: "android"
Exited with code 1
CircleCI received exit code 1
```

**Comment by dacevedo12** [comment]
Related to #226

**Comment by dsokal** [comment]
This seems like a great idea. However, currently, we're working on a totally new build service which will eventually replace `expo build:[android|ios]` and `turtle-cli`. With the new build service, the user/developer experience with logs should be better.
This means we don't want to introduce new features to `turte-cli`. Stay tuned!

Because of that, I'm closing this issue, sorry.
