### ISSUE TITLE
Turtle build:ios failing

### ISSUE THREAD

**Issue by raghu1286** [expo/turtle#136]
I'm trying to run build:ios command with all input options,
``` 
turtle build:ios -u <expo-user> -p <expo password> --team-id <apple team Id> --dist-p12-path <.p12> --provisioning-profile-path <profile>
```
But the build fails with error,

```
turtle[46551] ERROR: Failed to build standalone app
  err: Error: Please provide all required credentials- Apple Team ID, Distribution Certificate P12 (with password) and Provisioning Profile
      at prepareCredentials (/usr/local/lib/node_modules/turtle-cli/src/bin/commands/build/ios.ts:53:11)
      at /usr/local/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:69:33
  platform: "ios"
```
All the supplied values are correct, the expo build command with same inputs works fine.

Can anyone help as to what am I doing wrong.

Thanks!

**Comment by raghu1286** [comment]
Update:
I debugged the cli source code & found that the env var 'EXPO_IOS_DIST_P12_PASSWORD' wasn't being picked up. I passed that in the command directly & it started working,
```
EXPO_IOS_DIST_P12_PASSWORD=123456 turtle build:ios ...
```
This issue can be closed.
