### ISSUE TITLE
Error: ./configureAndroidSdk.sh exited with non-zero code: 1

### ISSUE THREAD

**Issue by Matwix** [expo/turtle#150]
Keep getting this error on Windows and on VM running Ubuntu when trying to setup Turtle CLI using the setup:android command everything else works fine except this step. Not sure what else I can do have tried to update everything but it's all the latest packages.

`Oct 22 12:20:23 turtle[9572] INFO:      ... 5 more
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 22 12:20:24 turtle[9572] ERROR: Failed to build standalone app
  err: Error: ./configureAndroidSdk.sh exited with non-zero code: 1
      at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:317:30)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:925:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
      ...
      at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (/@expo/xdl@56.2.2-alpha.2/src/detach/ExponentTools.ts:131:19)
      at _configureSdk (/usr/local/lib/node_modules/turtle-cli/src/bin/setup/android/sdk.ts:54:23)
      at <anonymous>
  platform: "android"`

**Comment by AlexandreLage** [comment]
I am also facing this bug :'(

`PS C:\WINDOWS\system32> turtle setup:android
Oct 23 16:40:24 turtle[63416] INFO:  Downloading Android SDK
  platform: "android"
  buildPhase: "setting up environment"
downloading [=================== ] 94% 0.7sOct 23 16:40:38 turtle[63416] INFO:  Decompressing Android SDK
  platform: "android"
  buildPhase: "setting up environment"
Oct 23 16:40:55 turtle[63416] INFO:  Configuring Android SDK, this may take a while
  platform: "android"
  buildPhase: "setting up environment"
Oct 23 16:40:56 turtle[63416] INFO:  /bin/bash: C:Usersbk_alageAppDataRoamingnpmnode_modulesturtle-cliscriptsandroidconfigureAndroidSdk.sh: No such file or directory
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 23 16:41:07 turtle[63416] ERROR: Failed to setup environment for android builds
  err: Error: ./configureAndroidSdk.sh exited with non-zero code: 127
      at ChildProcess.completionListener (C:\Users\bk_alage\AppData\Roaming\npm\node_modules\turtle-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:286:20)
      at ChildProcess.emit (events.js:198:13)
      at ChildProcess.EventEmitter.emit (domain.js:448:20)
      at ChildProcess.cp.emit (C:\Users\bk_alage\AppData\Roaming\npm\node_modules\turtle-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
      at maybeClose (internal/child_process.js:982:16)
      at Socket.stream.socket.on (internal/child_process.js:389:11)
      at Socket.emit (events.js:198:13)
      at Socket.EventEmitter.emit (domain.js:448:20)
      at Pipe._handle.close (net.js:606:12)
      ...
      at spawnAsync (C:\Users\bk_alage\AppData\Roaming\npm\node_modules\turtle-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (C:\@expo\xdl@56.2.2-alpha.2\src\detach\ExponentTools.ts:131:19)
      at _configureSdk (C:\Users\bk_alage\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\setup\android\sdk.ts:54:23)
  platform: "android"`

**Comment by sidor555** [comment]
Same Issue on Windows 10 - 64bit
`Oct 24 12:02:32 turtle[7416] ERROR: Failed to setup environment for android builds
  err: Error: ./configureAndroidSdk.sh exited with non-zero code: 4294967295
      at ChildProcess.completionListener (C:\Users\Utech BD\AppData\Roaming\npm\node_modules\turtle-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:286:20)
      at ChildProcess.emit (events.js:198:13)
      at ChildProcess.EventEmitter.emit (domain.js:448:20)
      at ChildProcess.cp.emit (C:\Users\Utech BD\AppData\Roaming\npm\node_modules\turtle-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
      at maybeClose (internal/child_process.js:982:16)
      at Socket.stream.socket.on (internal/child_process.js:389:11)
      at Socket.emit (events.js:198:13)
      at Socket.EventEmitter.emit (domain.js:448:20)
      at Pipe._handle.close (net.js:606:12)
      ...
      at spawnAsync (C:\Users\Utech BD\AppData\Roaming\npm\node_modules\turtle-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (C:\@expo\xdl@56.2.2-alpha.2\src\detach\ExponentTools.ts:131:19)
      at _configureSdk (C:\Users\Utech BD\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\setup\android\sdk.ts:54:23)
  platform: "android"`

**Comment by BrickmanRodrigo** [comment]
Same issue in Ubuntu 16.04 (Not a VM) when I try to run turtle setup:android

**Comment by julia-pol** [comment]
@esamelson  I have a similar problem
how by @Matwix 
what actions in this situation?

**Comment by dsokal** [comment]
Windows is not a supported platform, sorry.
I'm closing this issue because you didn't fill out the issue template.
