### ISSUE TITLE
turtle-cli crashing in Travis CI

### ISSUE THREAD

**Issue by MitchK** [expo/turtle#180]
### New Issue Checklist

- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md
).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- ~~**I enclosed the complete output when running turtle, including the stack trace and command used.**~~ too much output

### Issue Description
When running turtle-cli ```0.13.8``` in Travis CI on Ubuntu 16.04, it crashes with the following error logs. It has worked before, but recently our builds started crashing. Could this be a memory issue? It works when running locally. 

##### Command executed
```
npx turtle build:android \
  --keystore-path "${keystore_file}" \
  --keystore-alias "${EXPO_ANDROID_KEYSTORE_ALIAS}" \
  --type aab \
  --release-channel "${RELEASE_CHANNEL}" \
  -o "${ARTIFACT_PATH}"
```

##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre>...
Feb 9 08:21:29 turtle[5504] INFO:  Unable to strip library '/home/travis/.turtle/workingdir/android/sdk36/android-shell-app/app/build/intermediates/merged_native_libs/release/out/lib/x86/libjscexecutor.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Feb 9 08:21:29 turtle[5504] INFO:  R8: The rule `-keep class * extends com.facebook.react.bridge.JavaScriptModule {
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Feb 9 08:21:29 turtle[5504] INFO:    *;
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Feb 9 08:21:29 turtle[5504] INFO:  }` uses extends but actually matches implements.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Feb 9 08:21:29 turtle[5504] INFO:  R8: The rule `-keep class * extends com.facebook.react.bridge.NativeModule {
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Feb 9 08:21:29 turtle[5504] INFO:    *;
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Feb 9 08:21:29 turtle[5504] INFO:  }` uses extends but actually matches implements.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"9m
Feb 9 08:21:29 turtle[5504] INFO:  ----- End of the daemon log -----
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Feb 9 08:21:29 turtle[5504] INFO:  FAILURE: Build failed with an exception.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Feb 9 08:21:29 turtle[5504] INFO:  * What went wrong:
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Feb 9 08:21:29 turtle[5504] INFO:  Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Feb 9 08:21:29 turtle[5504] INFO:  * Try:
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Feb 9 08:21:29 turtle[5504] INFO:  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Feb 9 08:21:29 turtle[5504] INFO:  * Get more help at https://help.gradle.org
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Feb 9 08:21:30 turtle[5504] ERROR: Error: ./gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/home/travis/build/org/repo/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:300:26)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
    ...
    at spawnAsync (/home/travis/build/org/repo/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnAsyncThrowError (/@expo/xdl@57.4.0/src/detach/ExponentTools.ts:132:19)
    at buildShellAppAsync (/@expo/xdl@57.4.0/src/detach/AndroidShellApp.js:1240:11)
    at Object.createAndroidShellAppAsync (/@expo/xdl@57.4.0/src/detach/AndroidShellApp.js:357:5)
    at runShellAppBuilder (/home/travis/build/org/repo/node_modules/turtle-cli/src/builders/android.ts:87:5)
    at buildAndroid (/home/travis/build/org/repo/node_modules/turtle-cli/src/builders/android.ts:24:26)
    at /home/travis/build/org/repo/node_modules/turtle-cli/src/bin/utils/builder.ts:76:7
    at Command.<anonymous> (/home/travis/build/org/repo/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "android"
Feb 9 08:21:30 turtle[5504] ERROR: Failed to build standalone app
  err: Error: ./gradlew exited with non-zero code: 1
      at ChildProcess.completionListener (./node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:300:26)
      at ChildProcess.emit (events.js:210:5)
      at ChildProcess.EventEmitter.emit (domain.js:475:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
      ...
      at spawnAsync (./node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at spawnAsyncThrowError (/@expo/xdl@57.4.0/src/detach/ExponentTools.ts:132:19)
      at buildShellAppAsync (/@expo/xdl@57.4.0/src/detach/AndroidShellApp.js:1240:11)
      at Object.createAndroidShellAppAsync (/@expo/xdl@57.4.0/src/detach/AndroidShellApp.js:357:5)
      at runShellAppBuilder (./node_modules/turtle-cli/src/builders/android.ts:87:5)
      at buildAndroid (./node_modules/turtle-cli/src/builders/android.ts:24:26)
      at ./node_modules/turtle-cli/src/bin/utils/builder.ts:76:7
      at Command.<anonymous> (./node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "android"</pre>
</details>

### Environment

<details>
  <pre>   Expo CLI 3.11.9 environment info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.19.2 - ~/build/org/repo/node_modules/.bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    npmPackages:
      @types/expo: ^33.0.1 => 33.0.1
      @types/react: ^16.8.23 => 16.9.16
      @types/react-native: ^0.60.25 => 0.60.25
      @types/react-navigation: ^3.4.0 => 3.4.0
      expo: ^36.0.0 => 36.0.1
      react: ^16.12.0 => 16.12.0
      react-native: ^0.61.5 => 0.61.5
      react-navigation: ^4.0.10 => 4.0.10</pre>
</details>

**Comment by dsokal** [comment]
Hi @MitchK,
sorry for the delayed response. Are you still experiencing the issue? Unfortunately, the log output you enclosed seems to be too generic to tell anything. I encourage you to share **the complete log output** if you want to get help sooner.
However, yes, it may be related to the low memory limit. Try running your build again and/or increasing the limits.

**Comment by dsokal** [comment]
I'm closing this issue due to inactivity.

**Comment by MitchK** [comment]
hi @dsokal can you please re-open? the issue still persists, this time I tried it to run on GitHub actions. no luck.

Here is the full log file:
https://gist.github.com/MitchK/666dab9550a73e172976ce1b2e670bcd

This is my script:
https://gist.github.com/MitchK/15812e88f36970f5b08dc1c7d4a31256

**Comment by MitchK** [comment]
actually, nevermind. it seems to be a different error this time. looks like a key store issue 👍
