### ISSUE TITLE
turtle setup:android java connection timeout

### ISSUE THREAD

**Issue by Syedz15** [expo/turtle#181]
I get this output after updating the JAVA_OPTS:

Feb 12 18:01:21 turtle[23808] ERROR: Failed to setup environment for android builds
err: Error: ./configureAndroidSdk.sh exited with non-zero code: 1
at ChildProcess.completionListener (/usr/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
at Object.onceWrapper (events.js:286:20)
at ChildProcess.emit (events.js:198:13)
at ChildProcess.EventEmitter.emit (domain.js:448:20)
at maybeClose (internal/child_process.js:982:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
...
at spawnAsync (/usr/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
at Object.spawnAsyncThrowError (/@expo/xdl@57.4.0/src/detach/ExponentTools.ts:132:19)
at _configureSdk (/usr/lib/node_modules/turtle-cli/src/bin/setup/android/sdk.ts:54:23)
platform: "android"
[root@ip-10-157-155-173 mobile-native]# sudo update-alternatives --config java

There is 1 program that provides 'java'.

Selection Command
*+ 1 java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre/bin/java)

Enter to keep the current selection[+], or type selection number:
[root@ip-10-157-155-173 mobile-native]# $JAVA_HOME/bin/java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

**Comment by dsokal** [comment]
Hi!
Please fill out the issue template. The log output you provided is meaningless and too generic to figure something out.

**Comment by dsokal** [comment]
I'm closing this issue due to inactivity.
