### ISSUE TITLE
ValidationError: child "credentials" fails because [child "keystore" fails because ["keystore" is not allowed to be empty]]

### ISSUE THREAD

**Issue by hanselsen** [expo/turtle#208]
### New Issue Checklist

- [x ] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x ] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x ] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x ] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description
I am using a docker image with turtle-cli on it for CI/CD.  
The build step keeps failing.  The last lines are
`turtle build:android -t app-bundle --keystore-path ./keystore.jks --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS`
then a complete echo of the app.json.  
`turtle[10] INFO:  Using manifest: {"icon":"./images/app-icon.png","na...`
and then `ERROR: Failed to build standalone app`

##### Command executed
`turtle build:android -t app-bundle --keystore-path ./keystore.jks --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS`

##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre> 
[0KRunning with gitlab-runner 12.7.1 (003fe500)
[0;m[0K  on GitLab-ESX eb7TU1Yt
[0;msection_start:1586936656:prepare_executor
[0K[0KUsing Docker executor with image registry.gitlab.com/myapp/mycom/mobileapp/expo-build:android ...
[0;m[0KAuthenticating with credentials from $DOCKER_AUTH_CONFIG
[0;m[0KPulling docker image registry.gitlab.com/myapp/mycom/mobileapp/expo-build:android ...
[0;m[0KUsing docker image sha256:694c7c90d800c541373f78cdf4e2dc091e31393a9a3162000cd773f0bd30fd7a for registry.gitlab.com/myapp/mycom/mobileapp/expo-build:android ...
[0;msection_end:1586936931:prepare_executor
[0Ksection_start:1586936931:prepare_script
[0KRunning on runner-eb7TU1Yt-project-17655008-concurrent-0 via gitlab...
section_end:1586936938:prepare_script
[0Ksection_start:1586936938:get_sources
[0K[32;1mFetching changes with git depth set to 50...[0;m
Reinitialized existing Git repository in /builds/myapp/mycom/mobileapp/.git/
[32;1mChecking out f50f7844 as staging...[0;m
Removing node_modules/
Removing utils/i18n/translations/en-GB.json
Removing utils/i18n/translations/nl-NL.json

[32;1mSkipping Git submodules setup[0;m
section_end:1586936952:get_sources
[0Ksection_start:1586936952:restore_cache
[0K[32;1mChecking cache for staging-2...[0;m
No URL provided, cache will not be downloaded from shared cache server. Instead a local version of cache will be extracted.[0;m 
[32;1mSuccessfully extracted cache[0;m
section_end:1586937016:restore_cache
[0Ksection_start:1586937016:download_artifacts
[0Ksection_end:1586937017:download_artifacts
[0Ksection_start:1586937017:build_script
[0K[0KAuthenticating with credentials from $DOCKER_AUTH_CONFIG
[0;m[32;1m$ ls -al[0;m
total 952
drwxrwxrwx   11 root root   4096 Apr 15 07:50 .
drwxrwxrwx    4 root root   4096 Apr 15 06:17 ..
-rw-rw-rw-    1 root root     60 Apr 15 06:17 .babelrc
-rw-rw-rw-    1 root root    114 Apr 15 06:17 .buckconfig
drwxrwxrwx    2 root root   4096 Apr 15 06:17 .expo-shared
drwxrwxrwx    6 root root   4096 Apr 15 07:49 .git
-rw-rw-rw-    1 root root     16 Apr 15 06:17 .gitattributes
-rw-rw-rw-    1 root root   6029 Apr 15 06:17 .gitignore
-rw-rw-rw-    1 root root   1329 Apr 15 07:41 .gitlab-ci.yml
-rw-rw-rw-    1 root root   1345 Apr 15 06:17 App.js
-rw-rw-rw-    1 root root     13 Apr 15 06:17 README.md
-rw-rw-rw-    1 root root      0 Apr 15 06:17 mycomMobile.jks
drwxrwxrwx    5 root root   4096 Apr 15 06:17 android
-rw-rw-rw-    1 root root    882 Apr 15 06:17 app.json
drwxrwxrwx    3 root root   4096 Apr 15 06:17 assets
-rw-rw-rw-    1 root root    107 Apr 15 06:17 babel.config.js
-rw-rw-rw-    1 root root   1074 Apr 15 06:17 google-services.json
drwxrwxrwx    2 root root   4096 Apr 15 06:17 images
-rw-rw-rw-    1 root root     99 Apr 15 06:17 index.js
-rw-rw-rw-    1 root root    421 Apr 15 06:17 metro.config.js
drwxr-xr-x 1315 root root  40960 Apr 15 06:06 node_modules
-rw-rw-rw-    1 root root 823100 Apr 15 06:17 package-lock.json
-rw-rw-rw-    1 root root   2090 Apr 15 06:17 package.json
drwxrwxrwx    7 root root   4096 Apr 15 06:17 redux
drwxrwxrwx    5 root root   4096 Apr 15 06:17 ui
-rw-rw-rw-    1 root root    485 Apr 15 06:17 updateTranslations.js
drwxrwxrwx    8 root root   4096 Apr 15 06:17 utils
[32;1m$ turtle build:android --keystore-path ./mycomMobile.jks --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS[0;m
Apr 15 07:50:26 turtle[10] INFO:  [32mUsing manifest: {"icon":"./images/app-icon.png","name":"mycom","slug":"mycomMobile","splash":{"image":"./images/splash.png","imageUrl":"[OMITTED]"},"android":{"package":"com.myapp.mycom.mobile","versionCode":1,"googleServicesFile":"{\n  \"project_info\": {\n    \"project_number\": \"[OMITTED]\",\n    \"firebase_url\": \"[OMITTED]\",\n    \"project_id\": \"mycom-mobile\",\n    \"storage_bucket\": \"mycom-mobile.appspot.com\"\n  },\n  \"client\": [\n    {\n      \"client_info\": {\n        \"mobilesdk_app_id\": \"1:[OMITTED]:android:cbffcabd2c9f6875e157c7\",\n        \"android_client_info\": {\n          \"package_name\": \"com.myapp.mycom.mobile\"\n        }\n      },\n      \"oauth_client\": [\n        {\n          \"client_id\": \"596007076038-tj1gstfpsqv1vgk61oolpjbh7d997dr2.apps.googleusercontent.com\",\n          \"client_type\": 3\n        }\n      ],\n      \"api_key\": [\n        {\n          \"current_key\": \"[OMITTED]\"\n        }\n      ],\n      \"services\": {\n        \"appinvite_service\": {\n          \"other_platform_oauth_client\": [\n            {\n              \"client_id\": \"[OMITTED].apps.googleusercontent.com\",\n              \"client_type\": 3\n            }\n          ]\n        }\n      }\n    }\n  ],\n  \"configuration_version\": \"1\"\n}"},"iconUrl":"[OMITTED]","locales":{},"privacy":"unlisted","version":"1.0.0","platforms":["android"],"entryPoint":"node_modules/expo/AppEntry.js","sdkVersion":"37.0.0","description":"The mobile app for mycom","orientation":"portrait","dependencies":["@react-native-community/masked-view","@react-navigation/drawer","@react-navigation/native","@react-navigation/stack","axios","dayjs","expo","expo-asset-utils","expo-av","expo-background-fetch","expo-constants","expo-device","expo-file-system","expo-location","expo-permissions","expo-web-browser","i18next","i18next-icu","immutable","jwt-decode","react","react-dom","react-i18next","react-leaflet","react-native","react-native-gesture-handler","react-native-paper","react-native-reanimated","react-native-safe-area-context","react-native-screens","react-native-svg","react-native-text-input-mask","react-native-unimodules","react-native-web","react-native-webview","react-redux","redux","redux-axios-middleware","redux-immutable","redux-saga","reselect","styled-components","validator"],"packagerOpts":{"config":"metro.config.js","sourceExts":["expo.ts","expo.tsx","expo.js","expo.jsx","ts","tsx","js","jsx","json","wasm","svg"]},"id":"@mycom/mycomMobile","releaseId":"85babb1d-f341-4510-a7aa-415b2fe44217","revisionId":"1.0.0-r.esjOjdEPg","publishedTime":"2020-04-14T15:22:40.325Z","commitTime":"2020-04-14T15:22:40.530Z","bundleUrl":"[OMITTED]2F1.0.0%2Fb06e3f257e91898993513206412ef67a-37.0.0-android.js","releaseChannel":"default","hostUri":"exp.host/@mycom/mycomMobile"}[39m
[32m  platform: "android"[39m
[32m  buildPhase: "reading manifest"[39m
Apr 15 07:50:26 turtle[10] ERROR: [31mFailed to build standalone app[39m
[31m  err: ValidationError: child "credentials" fails because [child "keystore" fails because ["keystore" is not allowed to be empty]][39m
[31m      at Object.exports.process (/usr/local/lib/node_modules/turtle-cli/node_modules/joi/lib/errors.js:196:19)[39m
[31m      at internals.Object._validateWithOptions (/usr/local/lib/node_modules/turtle-cli/node_modules/joi/lib/types/any/index.js:675:31)[39m
[31m      at internals.Object.validate (/usr/local/lib/node_modules/turtle-cli/node_modules/joi/lib/types/any/index.js:709:21)[39m
[31m      at Object.sanitizeJob (/usr/local/lib/node_modules/turtle-cli/src/validator.ts:8:35)[39m
[31m      at /usr/local/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:86:25[39m
[31m      at processTicksAndRejections (internal/process/task_queues.js:97:5)[39m
[31m      at Command.<anonymous> (/usr/local/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)[39m
[31m  platform: "android"[39m
section_end:1586937026:build_script
[0Ksection_start:1586937026:after_script
[0Ksection_end:1586937028:after_script
[0Ksection_start:1586937028:upload_artifacts_on_failure
[0Ksection_end:1586937029:upload_artifacts_on_failure
[0K[31;1mERROR: Job failed: exit code 1
[0;m
 </pre>
</details>

### Environment

<details>
<pre>
Expo CLI 3.18.0 environment info:
    System:
      OS: Linux 4.9 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.16.2 - /usr/local/bin/node
      npm: 6.14.4 - /usr/local/bin/npm
    npmGlobalPackages:
      expo-cli: 3.18.0
  
  
turtle -V: 0.14.6
</pre>
</details>

**Comment by dsokal** [comment]
Hi!
Are you sure `./keystore.jks` exists and isn't empty? :)

**Comment by hanselsen** [comment]
Wow.. damn. How is this possible haha.  There goes 8 hours down the drain.

Thanks. Somehow `expo fetch:android:keystore` gave me an empty keystore file.

**Comment by dsokal** [comment]
I'm happy you've managed to fix the problem. That's strange that `expo fetch:android:keystore` gave you an empty keystore file. 
Do you happen to use the accounts feature? If so, would you mind submitting an issue to the https://github.com/expo/expo-cli repository? Thanks!

**Comment by hanselsen** [comment]
I cannot reproduce it, so I'm afraid it might be something on my side. A bug report would not be necessary I think.
