### ISSUE TITLE
Cannot build Android APK on local machine

### ISSUE THREAD

**Issue by doubleh311** [expo/turtle#266]
### New Issue Checklist

- [ ] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [ ] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [ ] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [ ] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [ ] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description
I have setup to use turtle on my local machine to build apk file for Android and encounter the error that I have not found any solution yet.
The build command terminated with error on saving some Icons to disk.
I have looked into the repo xdl in Expo but I found it was archived and cannot find any file named AndroidIcons.ts as in the error description to view

##### Command executed
expo export --dev --public-url http://127.0.0.1:8000
turtle build:android --type apk
--keystore-path ./stagingKey/stagingKey.jks 
--keystore-alias "xxxxxxbWVuZ2xpc2xxxxxxxxxx"
--allow-non-https-public-url 
--public-url http://127.0.0.1:8000/android-index.json 
--release-channel staging

##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre> 
platform: "android"
  buildPhase: "reading manifest"
(node:350) UnhandledPromiseRejectionWarning: Error: Failed to save icon file to disk. (Error: Request failed with status code 404)
    at _resizeIconsAsync (/@expo/xdl@58.0.13/src/detach/AndroidIcons.ts:62:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at createAndWriteIconsToPathAsync (/@expo/xdl@58.0.13/src/detach/AndroidIcons.ts:150:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:350) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:350) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. </pre>
</details>

### Environment
Project: Expo SDK 38
Expo: 3.27.13
Turtle: 0.18.3
Ubuntu: 20.4 with WSL2 on Windows 10

**Comment by dons20** [comment]
It's been a while but nobody has attempted to answer this. Have you found a solution/workaround?

* I would start by updating the core dependencies, `turtle-cli` and `expo-cli` namely.
* Try to run your terminal as an admin.
* Check the icon that your manifest is pointing to, and verify its location, as well as format. You can try omitting the icon for debugging as well.
* I've had successful builds when I navigate to my `/mnt/c/project/directory` and run the commands from there. E.g. 
  ```bash
  cd /mnt/c/project/directory && \
  rm -rf dist && \
  expo export --dev --public-url http://127.0.0.1:8000 \
  # Ensure your local http server is running if you have any trouble
  ```
