### ISSUE TITLE
"timeout of 20000ms exceeded" during turtle build:android

### ISSUE THREAD

**Issue by mbpictures** [expo/turtle#269]
### New Issue Checklist

- [ X] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [X ] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [ X] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [X ] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [ X] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description
I've written a python script to automate the export and bundle of my expo project. When I run the command to export my project "turtle build:android --type apk --keystore-path PATH --keystore-alias ALIAS --allow-non-https-public-url --public-url http://127.0.0.1:8000/android-index.json" and "python -m http.server" before, everything works. When I use the same commands through the script I get a "timeout of 20000ms exceeded" error.

##### Command executed
```Python
    os.chdir(dist_path)

    handler_bundler = http.server.SimpleHTTPRequestHandler
    http_bundle = socketserver.TCPServer(("0.0.0.0", PORT), handler_bundler)
    thread_bundle = threading.Thread(target=http_bundle.serve_forever)
    thread_bundle.daemon = True
    thread_bundle.start()

    env_var = os.environ.copy()
    env_var["EXPO_ANDROID_KEYSTORE_PASSWORD"] = args.keystore_password
    env_var["EXPO_ANDROID_KEY_PASSWORD"] = args.key_password
    subprocess.run([
        "turtle",
        f"build:{args.target}",
        "--type",
        "apk",
        "--keystore-path",
        keystore_path,
        "--keystore-alias",
        args.key_alias,
        "--allow-non-https-public-url",
        "--public-url",
        f"http://127.0.0.1:{PORT}/{args.target}-index.json",
        "-o",
        os.path.join(dist_path, "DecisionMaker.apk"),
        project_path
    ], env=env_var)
```

##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre>Starting Metro Bundler.
Building iOS bundle
127.0.0.1 - - [20/Oct/2020 22:39:27] "GET /dist/ HTTP/1.1" 200 -
127.0.0.1 - - [20/Oct/2020 22:39:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Oct/2020 22:39:29] "GET /dist/bundles/ HTTP/1.1" 200 -
127.0.0.1 - - [20/Oct/2020 22:39:30] "GET / HTTP/1.1" 200 -
Building Android bundle
Finished building JavaScript bundle in 8358ms.
Building source maps
Finished building JavaScript bundle in 7820ms.
Finished building JavaScript bundle in 2469ms.
Finished building JavaScript bundle in 2403ms.
Building asset maps
Finished building JavaScript bundle in 7978ms.
Finished building JavaScript bundle in 8066ms.
Finished saving JS Bundles.
Analyzing assets
Saving assets
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/AntDesign.ttf
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/AntDesign.json
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Entypo.ttf
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/Entypo.json
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/EvilIcons.ttf
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/EvilIcons.json
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Feather.ttf
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/Feather.json
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Fontisto.ttf
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/Fontisto.json
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome.ttf
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/FontAwesome.json
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/FontAwesome5Free.json
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/FontAwesome5Free_meta.json
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome5_Regular.ttf
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome5_Solid.ttf
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome5_Brands.ttf
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Foundation.ttf
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/Foundation.json
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Ionicons.ttf
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/Ionicons.json
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/MaterialCommunityIcons.ttf
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/MaterialCommunityIcons.json
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/MaterialIcons.ttf
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/MaterialIcons.json
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Octicons.ttf
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/Octicons.json
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/SimpleLineIcons.ttf
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/SimpleLineIcons.json
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Zocial.ttf
saving /node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/Zocial.json
saving /node_modules/react-native-paper/src/assets/back-chevron.png
saving /node_modules/@googlemaps/google-maps-services-js/package.json
saving /node_modules/@react-navigation/stack/src/views/assets/back-icon@1x.ios.png
saving /node_modules/@react-navigation/stack/src/views/assets/back-icon@1.5x.ios.png
saving /node_modules/@react-navigation/stack/src/views/assets/back-icon@2x.ios.png
saving /node_modules/@react-navigation/stack/src/views/assets/back-icon@3x.ios.png
saving /node_modules/@react-navigation/stack/src/views/assets/back-icon@4x.ios.png
saving /node_modules/@react-navigation/stack/src/views/assets/back-icon-mask.png
saving /node_modules/@react-navigation/stack/src/views/assets/back-icon@1x.android.png
saving /node_modules/@react-navigation/stack/src/views/assets/back-icon@1.5x.android.png
saving /node_modules/@react-navigation/stack/src/views/assets/back-icon@2x.android.png
saving /node_modules/@react-navigation/stack/src/views/assets/back-icon@3x.android.png
saving /node_modules/@react-navigation/stack/src/views/assets/back-icon@4x.android.png
saving /assets/icon.png
saving /assets/splash.png
Files successfully saved.

Processing asset bundle patterns:
- /mnt/a/Projects/DecisionMaker/**/*
Export was successful. Your exported files can be found in dist
INFO: BUNDLING APK
127.0.0.1 - - [20/Oct/2020 22:40:55] "GET /android-index.json HTTP/1.1" 200 -
Oct 20 22:40:55 turtle[443] INFO:  Using manifest: {
  "name": "DecisionMaker",
  "slug": "DecisionMaker",
  "version": "1.0.0",
  "orientation": "portrait",
  "icon": "./assets/icon.png",
  "splash": {
    "image": "./assets/splash.png",
    "resizeMode": "contain",
    "backgroundColor": "#ffffff",
    "imageUrl": "http://127.0.0.1:8000/assets/b8895f17edbefb9f51b1f863c9811e44"
  },
  "updates": {
    "enabled": false,
    "fallbackToCacheTimeout": 0
  },
  "ios": {
    "supportsTablet": true
  },
  "web": {
    "favicon": "./assets/favicon.png"
  },
  "android": {
    "package": "com.lightwaveinteractive.decisionmaker",
    "versionCode": 1
  },
  "sdkVersion": "39.0.0",
  "platforms": [
    "ios",
    "android",
    "web"
  ],
  "locales": {},
  "iconUrl": "http://127.0.0.1:8000/assets/41aba486029b982d6f7773e6eed0f5b4",
  "bundledAssets": [
    "asset_3a2ba31570920eeb9b1d217cabe58315.ttf",
    "asset_8b12b3e16d591abc926165fa8f760e3b.json",
    "asset_744ce60078c17d86006dd0edabcd59a7.ttf",
    "asset_461d9bba8b6a3c91675039df12cfe6ca.json",
    "asset_140c53a7643ea949007aa9a282153849.ttf",
    "asset_94c4ffdcbffeb0570c635d7f8edd8a25.json",
    "asset_ca9ce9ff0676a9b04ef0f8a3ad17dd08.ttf",
    "asset_54a5c98d22f313098b3dbe2d5b2e87ba.json",
    "asset_b49ae8ab2dbccb02c4d11caaacf09eab.ttf",
    "asset_39843e5d52a6c5c42d5abdb0b34bcaa6.json",
    "asset_b06871f281fee6b241d60582ae9369b9.ttf",
    "asset_f1f91feb805137c9283fb766620ec5eb.json",
    "asset_09dd345dbd4ec5a0874841d5749ac153.json",
    "asset_0886a6b127c6057cee83f9c65c7ffd62.json",
    "asset_f6c6f6c8cb7784254ad00056f6fbd74e.ttf",
    "asset_b70cea0339374107969eb53e5b1f603f.ttf",
    "asset_c39278f7abfc798a241551194f55e29f.ttf",
    "asset_e20945d7c929279ef7a6f1db184a4470.ttf",
    "asset_60668d999bbaf663420340f7bdd580d7.json",
    "asset_b2e0fc821c6886fb3940f85a3320003e.ttf",
    "asset_3e6805fbc794680014716b8c752f20b8.json",
    "asset_3c851d60ad5ef3f2fe43ebd263490d78.ttf",
    "asset_1a0e3525dd5df87e77057204129a5e6e.json",
    "asset_a37b0c01c0baf1888ca812cc0508f6e2.ttf",
    "asset_7e078700f0c35367a56c5bbb2047dda7.json",
    "asset_8e7f807ef943bff1f6d3c2c6e0f3769e.ttf",
    "asset_fdc01171a7a7ea76b187afcd162dee7d.json",
    "asset_d2285965fe34b05465047401b8595dd0.ttf",
    "asset_647543ebfccf6e5495434383598453d1.json",
    "asset_5cdf883b18a5651a29a4d1ef276d2457.ttf",
    "asset_74d124a3caeac2bea111f3ca2f2dd34a.json",
    "asset_2379ae894c2c9f63b852a9f3676c2763.png",
    "asset_b39c12a6c1af7ff8e020f70c90bf93f2.json",
    "asset_7d40544b395c5949f4646f5e150fe020.png",
    "asset_cdd04e13d4ec83ff0cd13ec8dabdc341.png",
    "asset_a132ecc4ba5c1517ff83c0fb321bc7fc.png",
    "asset_0ea69b5077e7c4696db85dbcba75b0e1.png",
    "asset_f5b790e2ac193b3d41015edb3551f9b8.png",
    "asset_5223c8d9b0d08b82a5670fb5f71faf78.png",
    "asset_778ffc9fe8773a878e9c30a6304784de.png",
    "asset_376d6a4c7f622917c39feb23671ef71d.png",
    "asset_c79c3606a1cf168006ad3979763c7e0c.png",
    "asset_02bc1fa7c0313217bde2d65ccbff40c9.png",
    "asset_35ba0eaec5a4f5ed12ca16fabeae451d.png"
  ],
  "assetUrlOverride": "./assets",
  "publishedTime": "2020-10-20T20:40:54.035Z",
  "commitTime": "2020-10-20T20:40:54.035Z",
  "releaseId": "928a6445-addf-4018-a6b5-234db985ceca",
  "revisionId": "6kwx9gQAWj",
  "developer": {
    "tool": "exp"
  },
  "id": "@anonymous/DecisionMaker",
  "bundleUrl": "http://127.0.0.1:8000/bundles/android-8f551efab3c4b0817b0a1f4fc1bd5931.js",
  "platform": "android",
  "dependencies": [
    "@egjs/hammerjs",
    "@googlemaps/google-maps-services-js",
    "@react-native-community/async-storage",
    "@react-native-community/masked-view",
    "@react-navigation/native",
    "@react-navigation/stack",
    "axios",
    "expo",
    "expo-status-bar",
    "react",
    "react-art",
    "react-dom",
    "react-native",
    "react-native-gesture-handler",
    "react-native-paper",
    "react-native-reanimated",
    "react-native-safe-area-context",
    "react-native-screens",
    "react-native-snap-carousel",
    "react-native-web",
    "react-router-dom",
    "react-router-native",
    "react-scripts",
    "expo-location",
    "expo-permissions"
  ]
}
  platform: "android"
  buildPhase: "reading manifest"
Oct 20 22:40:55 turtle[443] INFO:  Starting build process
  platform: "android"
  buildPhase: "starting builder"
Oct 20 22:40:55 turtle[443] INFO:  ImageUtils: setting image functions to alternative sharp implementations
  platform: "android"
  buildPhase: "icons setup"
Oct 20 22:40:55 turtle[443] INFO:  Resolving universal modules dependencies
  platform: "android"
  buildPhase: "resolve native modules"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-ads-admob:8.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding @unimodules/core:5.5.1
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-ads-facebook:8.4.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-analytics-amplitude:8.3.1
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-analytics-segment:9.0.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding unimodules-constants-interface:5.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-app-auth:9.2.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-apple-authentication:2.2.1
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding @unimodules/react-native-adapter:5.6.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding unimodules-app-loader:1.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding unimodules-font-interface:5.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding unimodules-image-loader-interface:5.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding unimodules-permissions-interface:5.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-application:2.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-av:8.6.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-background-fetch:8.5.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-task-manager:8.5.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding unimodules-task-manager-interface:5.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-barcode-scanner:9.0.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding unimodules-barcode-scanner-interface:5.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-battery:3.0.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-blur:8.2.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-brightness:8.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-calendar:8.5.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-camera:9.0.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding unimodules-camera-interface:5.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding unimodules-face-detector-interface:5.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding unimodules-file-system-interface:5.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-cellular:2.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-constants:9.2.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-contacts:8.5.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-crypto:8.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-device:2.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-document-picker:8.4.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-error-recovery:1.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-face-detector:8.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-facebook:9.0.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-file-system:9.2.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-firebase-analytics:2.5.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-firebase-core:1.2.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-font:8.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-gl:9.1.1
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-gl-cpp:9.1.2
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-gl-cpp-legacy:8.4.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-google-sign-in:8.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-haptics:8.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-image-loader:1.2.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-image-manipulator:8.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-image-picker:9.1.1
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-permissions:9.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-in-app-purchases:9.0.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-intent-launcher:8.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-keep-awake:8.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-linear-gradient:8.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-local-authentication:9.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-localization:9.0.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-location:9.0.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-mail-composer:8.4.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-media-library:9.2.1
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-module-template:8.4.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-network:2.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-notifications:0.7.2
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-payments-stripe:8.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-print:9.1.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-screen-capture:1.1.1
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-screen-orientation:2.0.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-secure-store:9.2.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-sensors:9.1.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding unimodules-sensors-interface:5.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-sharing:8.4.1
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-sms:8.3.1
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-speech:8.4.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-splash-screen:0.6.2
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-sqlite:8.4.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-store-review:2.2.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-updates:0.3.3
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-video-thumbnails:4.3.0
  platform: "android"
Oct 20 22:40:55 turtle[443] INFO:  Adding expo-web-browser:8.5.0
  platform: "android"
Oct 20 22:40:56 turtle[443] INFO:  Using manifest: {"name":"DecisionMaker","slug":"DecisionMaker","version":"1.0.0","orientation":"portrait","icon":"./assets/icon.png","splash":{"image":"./assets/splash.png","resizeMode":"contain","backgroundColor":"#ffffff","imageUrl":"http://127.0.0.1:8000/assets/b8895f17edbefb9f51b1f863c9811e44"},"updates":{"enabled":false,"fallbackToCacheTimeout":0},"ios":{"supportsTablet":true},"web":{"favicon":"./assets/favicon.png"},"android":{"package":"com.lightwaveinteractive.decisionmaker","versionCode":1},"sdkVersion":"39.0.0","platforms":["ios","android","web"],"locales":{},"iconUrl":"http://127.0.0.1:8000/assets/41aba486029b982d6f7773e6eed0f5b4","bundledAssets":["asset_3a2ba31570920eeb9b1d217cabe58315.ttf","asset_8b12b3e16d591abc926165fa8f760e3b.json","asset_744ce60078c17d86006dd0edabcd59a7.ttf","asset_461d9bba8b6a3c91675039df12cfe6ca.json","asset_140c53a7643ea949007aa9a282153849.ttf","asset_94c4ffdcbffeb0570c635d7f8edd8a25.json","asset_ca9ce9ff0676a9b04ef0f8a3ad17dd08.ttf","asset_54a5c98d22f313098b3dbe2d5b2e87ba.json","asset_b49ae8ab2dbccb02c4d11caaacf09eab.ttf","asset_39843e5d52a6c5c42d5abdb0b34bcaa6.json","asset_b06871f281fee6b241d60582ae9369b9.ttf","asset_f1f91feb805137c9283fb766620ec5eb.json","asset_09dd345dbd4ec5a0874841d5749ac153.json","asset_0886a6b127c6057cee83f9c65c7ffd62.json","asset_f6c6f6c8cb7784254ad00056f6fbd74e.ttf","asset_b70cea0339374107969eb53e5b1f603f.ttf","asset_c39278f7abfc798a241551194f55e29f.ttf","asset_e20945d7c929279ef7a6f1db184a4470.ttf","asset_60668d999bbaf663420340f7bdd580d7.json","asset_b2e0fc821c6886fb3940f85a3320003e.ttf","asset_3e6805fbc794680014716b8c752f20b8.json","asset_3c851d60ad5ef3f2fe43ebd263490d78.ttf","asset_1a0e3525dd5df87e77057204129a5e6e.json","asset_a37b0c01c0baf1888ca812cc0508f6e2.ttf","asset_7e078700f0c35367a56c5bbb2047dda7.json","asset_8e7f807ef943bff1f6d3c2c6e0f3769e.ttf","asset_fdc01171a7a7ea76b187afcd162dee7d.json","asset_d2285965fe34b05465047401b8595dd0.ttf","asset_647543ebfccf6e5495434383598453d1.json","asset_5cdf883b18a5651a29a4d1ef276d2457.ttf","asset_74d124a3caeac2bea111f3ca2f2dd34a.json","asset_2379ae894c2c9f63b852a9f3676c2763.png","asset_b39c12a6c1af7ff8e020f70c90bf93f2.json","asset_7d40544b395c5949f4646f5e150fe020.png","asset_cdd04e13d4ec83ff0cd13ec8dabdc341.png","asset_a132ecc4ba5c1517ff83c0fb321bc7fc.png","asset_0ea69b5077e7c4696db85dbcba75b0e1.png","asset_f5b790e2ac193b3d41015edb3551f9b8.png","asset_5223c8d9b0d08b82a5670fb5f71faf78.png","asset_778ffc9fe8773a878e9c30a6304784de.png","asset_376d6a4c7f622917c39feb23671ef71d.png","asset_c79c3606a1cf168006ad3979763c7e0c.png","asset_02bc1fa7c0313217bde2d65ccbff40c9.png","asset_35ba0eaec5a4f5ed12ca16fabeae451d.png"],"assetUrlOverride":"./assets","publishedTime":"2020-10-20T20:40:54.035Z","commitTime":"2020-10-20T20:40:54.035Z","releaseId":"928a6445-addf-4018-a6b5-234db985ceca","revisionId":"6kwx9gQAWj","developer":{"tool":"exp"},"id":"@anonymous/DecisionMaker","bundleUrl":"http://127.0.0.1:8000/bundles/android-8f551efab3c4b0817b0a1f4fc1bd5931.js","platform":"android","dependencies":["@egjs/hammerjs","@googlemaps/google-maps-services-js","@react-native-community/async-storage","@react-native-community/masked-view","@react-navigation/native","@react-navigation/stack","axios","expo","expo-status-bar","react","react-art","react-dom","react-native","react-native-gesture-handler","react-native-paper","react-native-reanimated","react-native-safe-area-context","react-native-screens","react-native-snap-carousel","react-native-web","react-router-dom","react-router-native","react-scripts","expo-location","expo-permissions"]}
  platform: "android"
  buildPhase: "reading manifest"
127.0.0.1 - - [20/Oct/2020 22:41:00] "GET / HTTP/1.1" 200 -
Oct 20 22:41:18 turtle[443] ERROR: Error: timeout of 20000ms exceeded
    at createError (/usr/local/lib/node_modules/turtle-cli/node_modules/axios/lib/core/createError.js:16:15)
    at Timeout.handleRequestTimeout (/usr/local/lib/node_modules/turtle-cli/node_modules/axios/lib/adapters/http.js:252:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  platform: "android"
Oct 20 22:41:18 turtle[443] ERROR: Failed to build standalone app
  err: Error: timeout of 20000ms exceeded
      at createError (/usr/local/lib/node_modules/turtle-cli/node_modules/axios/lib/core/createError.js:16:15)
      at Timeout.handleRequestTimeout (/usr/local/lib/node_modules/turtle-cli/node_modules/axios/lib/adapters/http.js:252:16)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)
  platform: "android"</pre>
</details>

### Environment

<details>
  <pre>  Expo CLI 3.28.1 environment info:
    System:
      OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 10.19.0 - /usr/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
    npmPackages:
      @expo/webpack-config: ^0.12.39 => 0.12.39
      expo: ~39.0.2 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: ^16.14.0 => 16.14.0
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ^0.14.1 => 0.14.2
    npmGlobalPackages:
      expo-cli: 3.28.1
    Expo Workflow: managed</pre>
</details>

**Comment by mbpictures** [comment]
Maybe it's related to the port? I removed the part, where the projects get exported (which uses a HTTP server on 8000) and now (using 8000 for the turtle process) everything is working while using 8000 doesn't work

**Comment by trajano** [comment]
I'm getting a similar problem is there a way of increasing the timeout?  Not sure what it's waiting 20 seconds for.
