### ISSUE TITLE
turtle build:ios gives "Error: xcrun exited with non-zero code: 126"

### ISSUE THREAD

**Issue by philwingfield** [expo/turtle#322]
### New Issue Checklist

- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description
I am running turtle build:ios on macos and and getting the error detailed below. The expo:publish and turtle build:android work fine and produce an aab as expected.

##### Command executed
turtle build:ios --team-id **** --provisioning-profile-path ./MobileApp.mobileprovision --dist-p12-path ./MobileApp_dist.p12

##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre> 
Aug 6 13:10:12 turtle[77806] INFO:  Using manifest: {
  "ios": {
    "infoPlist": {
      "UIBackgroundModes": [
        "location",
        "fetch",
        "audio"
      ],
      "NSCameraUsageDescription": "Camera permission required to allow you to take a profile picture for use in your profile.",
      "NSMotionUsageDescription": "This permission is not needed by the app, but it is required by an underlying API. If you see this dialog, contact us.",
      "NSContactsUsageDescription": "This permission is not needed by the app, but it is required by an underlying API. If you see this dialog, contact us.",
      "NSCalendarsUsageDescription": "This permission is not needed by the app, but it is required by an underlying API. If you see this dialog, contact us.",
      "NSRemindersUsageDescription": "This permission is not needed by the app, but it is required by an underlying API. If you see this dialog, contact us.",
      "NSMicrophoneUsageDescription": "This permission is not needed by the app, but it is required by an underlying API. If you see this dialog, contact us.",
      "NSPhotoLibraryUsageDescription": "Media access required to allow you to upload an existing photo for use in your profile.",
      "NSLocationAlwaysUsageDescription": "Location needed to track your running session, including while the screen is off. Location is only used when running.",
      "NSPhotoLibraryAddUsageDescription": "This permission is not needed by the app, but it is required by an underlying API. If you see this dialog, contact us.",
      "NSLocationAlwaysAndWhenInUseUsageDescription": "Location data needed to track you as you run your session, including while the screen is off. Location is only used when running."
    },
    "supportsTablet": false,
    "bundleIdentifier": "uk.co.levelstudio.zoazi.expo"
  },
  "icon": "./assets/img/icon.png",
  "name": "Zoazi Running Coach",
  "slug": "MobileApp",
  "splash": {
    "image": "./assets/img/splash.png",
    "imageUrl": "https://d1wp6m56sqw74a.cloudfront.net/~assets/e5f88b5c2d7d1476c336865713938513",
    "resizeMode": "contain",
    "backgroundColor": "#236AFA"
  },
  "android": {
    "package": "uk.co.levelstudio.zoazi.expo",
    "permissions": [
      "ACCESS_COARSE_LOCATION",
      "ACCESS_FINE_LOCATION",
      "ACCESS_BACKGROUND_LOCATION",
      "CAMERA",
      "READ_EXTERNAL_STORAGE",
      "WRITE_EXTERNAL_STORAGE"
    ],
    "versionCode": 30040,
    "adaptiveIcon": {
      "backgroundColor": "#236AFA",
      "foregroundImage": "./assets/img/drawable-hdpi/adaptive_blue.png",
      "foregroundImageUrl": "https://d1wp6m56sqw74a.cloudfront.net/~assets/15e2738df471a8906d9aefc4cfcc0fde"
    },
    "useNextNotificationsApi": true
  },
  "iconUrl": "https://d1wp6m56sqw74a.cloudfront.net/~assets/abf695b5db1eb2858754a3f98a155e47",
  "locales": {},
  "privacy": "unlisted",
  "updates": {
    "enabled": false
  },
  "version": "3.0.40",
  "platforms": [
    "ios",
    "android"
  ],
  "sdkVersion": "42.0.0",
  "orientation": "portrait",
  "dependencies": [
    "@ptomasroos/react-native-multi-slider",
    "@react-native-community/datetimepicker",
    "@react-native-community/masked-view",
    "@react-native-community/netinfo",
    "@react-navigation/bottom-tabs",
    "@react-navigation/native",
    "@react-navigation/stack",
    "@rnhooks/keyboard",
    "d3",
    "d3-array",
    "d3-axis",
    "d3-format",
    "d3-scale",
    "d3-shape",
    "emoji-regex",
    "expo",
    "expo-analytics",
    "expo-av",
    "expo-battery",
    "expo-constants",
    "expo-device",
    "expo-facebook",
    "expo-file-system",
    "expo-font",
    "expo-image-manipulator",
    "expo-image-picker",
    "expo-intent-launcher",
    "expo-linear-gradient",
    "expo-linking",
    "expo-localization",
    "expo-location",
    "expo-notifications",
    "expo-permissions",
    "expo-speech",
    "expo-task-manager",
    "expo-web-browser",
    "formik",
    "haversine",
    "i18n-js",
    "immer",
    "moment",
    "moment-range",
    "moment-timezone",
    "react",
    "react-dom",
    "react-native",
    "react-native-a-beep",
    "react-native-appearance",
    "react-native-aws3",
    "react-native-calendars",
    "react-native-chart-kit",
    "react-native-confetti",
    "react-native-error-boundary",
    "react-native-gesture-handler",
    "react-native-get-random-values",
    "react-native-linear-gradient",
    "react-native-maps",
    "react-native-modal",
    "react-native-modal-datetime-picker",
    "react-native-paper",
    "react-native-parsed-text",
    "react-native-picker-select",
    "react-native-progress",
    "react-native-reanimated",
    "react-native-responsive-screen",
    "react-native-safe-area-context",
    "react-native-safe-area-view",
    "react-native-screens",
    "react-native-snap-carousel",
    "react-native-svg",
    "react-native-svg-charts",
    "react-native-swipe-gestures",
    "react-native-swipeable",
    "react-native-tab-view",
    "react-native-vector-icons",
    "react-native-webview",
    "react-redux",
    "reanimated-bottom-sheet",
    "redux",
    "redux-persist",
    "reselect",
    "rn-toggle-switch",
    "shorthash",
    "sprintf-js",
    "svg-path-properties",
    "uuid",
    "yup"
  ],
  "primaryColor": "#236AFA",
  "bundledAssets": [
    "asset_4d882c2509eaa724d486f6dac753b8f5.json",
    "asset_9f05530c64a774d02410e02d0d1554f3.json",
    "asset_2dd3a3e61fb252e9dcb6af9e6aec37ab.json",
    "asset_bcc034acc51c5c8f92c257a28ec9a1d6.json",
    "asset_23bfef5a2cc986befc66df420cb56889.json",
    "asset_2ac32dec71143dccca808a592a85eb9f.json",
    "asset_59e1d07580be5bc3c66af78930b04b98.json",
    "asset_763ab407d457cabe6a24d9b35e9b32fe.jpg",
    "asset_1dbf1f43f1a7a29bec48edbb715a6c56.jpg",
    "asset_70e1ca5596735c8284ecea492a427205.jpg",
    "asset_7d40544b395c5949f4646f5e150fe020.png",
    "asset_cdd04e13d4ec83ff0cd13ec8dabdc341.png",
    "asset_a132ecc4ba5c1517ff83c0fb321bc7fc.png",
    "asset_0ea69b5077e7c4696db85dbcba75b0e1.png",
    "asset_f5b790e2ac193b3d41015edb3551f9b8.png",
    "asset_5223c8d9b0d08b82a5670fb5f71faf78.png",
    "asset_a8b98e516b7e5a7770f0bfec609f2d8e.png",
    "asset_3fc49f4d75a5a92eea5f3b1f9a8b12e4.png",
    "asset_6a5a5ec704600ad5cf355bcd746719de.png",
    "asset_e20c2fe873237189a9b2bc2768c022e0.png",
    "asset_7811e294b4c9f572643e835b85f9f696.png",
    "asset_eaf316bee4eabbb6ff76a664e853b4ba.png",
    "asset_166afe3a6c4c45803490e21b596041bf.png",
    "asset_b49d35b0fe9bfb9a3f6f248a17852e5c.png",
    "asset_28cb2ca20c6bc7d40ef0804a2b053509.png",
    "asset_f86a4012c286f0a10bc6e9f91b7b9f05.png",
    "asset_e8cb3fb92dc534dcf53d8564624f0b36.png",
    "asset_9c7a702c163c6e28d619603bbca7a036.png",
    "asset_3a2ba31570920eeb9b1d217cabe58315.ttf",
    "asset_8b12b3e16d591abc926165fa8f760e3b.json",
    "asset_744ce60078c17d86006dd0edabcd59a7.ttf",
    "asset_461d9bba8b6a3c91675039df12cfe6ca.json",
    "asset_140c53a7643ea949007aa9a282153849.ttf",
    "asset_94c4ffdcbffeb0570c635d7f8edd8a25.json",
    "asset_e766963327e0a89f9ec2ba88646b6177.ttf",
    "asset_83d0d0700e24da7297be10ae931dd38f.json",
    "asset_b49ae8ab2dbccb02c4d11caaacf09eab.ttf",
    "asset_39843e5d52a6c5c42d5abdb0b34bcaa6.json",
    "asset_b06871f281fee6b241d60582ae9369b9.ttf",
    "asset_f1f91feb805137c9283fb766620ec5eb.json",
    "asset_276ee4e65ded9a91cfe0be813e95e42d.json",
    "asset_8d09f2281ac9c99f438fb1c0b5c66d20.json",
    "asset_db78b9359171f24936b16d84f63af378.ttf",
    "asset_1ab236ed440ee51810c56bd16628aef0.ttf",
    "asset_13685372945d816a2b474fc082fd9aaa.ttf",
    "asset_e20945d7c929279ef7a6f1db184a4470.ttf",
    "asset_60668d999bbaf663420340f7bdd580d7.json",
    "asset_b3263095df30cb7db78c613e73f9499a.ttf",
    "asset_bb0e1479c256e29e7ee92433a5e4b43e.json",
    "asset_6a2ddad1092a0a1c326b6d0e738e682b.ttf",
    "asset_f337aab857fd04843f0a882ec5726fb3.json",
    "asset_8ef52a15e44481b41e7db3c7eaf9bb83.ttf",
    "asset_fdbedb7e67aa7c0ecad83d9c2fa4dfba.json",
    "asset_8e7f807ef943bff1f6d3c2c6e0f3769e.ttf",
    "asset_fdc01171a7a7ea76b187afcd162dee7d.json",
    "asset_d2285965fe34b05465047401b8595dd0.ttf",
    "asset_647543ebfccf6e5495434383598453d1.json",
    "asset_5cdf883b18a5651a29a4d1ef276d2457.ttf",
    "asset_74d124a3caeac2bea111f3ca2f2dd34a.json",
    "asset_a2a8fbdb83b240fb68ef876d91655852.jpg",
    "asset_de6986e479609849ee1a3f682a856b1e.jpg",
    "asset_9942ef3cf8a27f556654458a783f15ab.jpg",
    "asset_2379ae894c2c9f63b852a9f3676c2763.png",
    "asset_fa3161bb5f376b3c49e69bb2db78aaf5.png",
    "asset_5f9d05e1376de85578c4fa5bb10854f5.png",
    "asset_3403959830b3243d64441a772fae7f0f.png",
    "asset_f78deb0db0c1d2d93df06f239b34cfe2.png",
    "asset_aaa229cd8e6bb9fba5457aeff8eb0ece.png",
    "asset_398a8a1eed66ef02341911ef6b83fe2a.png",
    "asset_f93406ce90e2f52216d62cd77b852c9c.png",
    "asset_47ce6e77f039020ee2e76a10c1e988e9.png",
    "asset_5853522a69e69fa51aa8fe9be98ec913.jpg",
    "asset_7d89b31cb141f212c0d18f7440396431.jpg",
    "asset_c46eea51926b199a343d255acd39568d.mp3",
    "asset_16a311f2ed1ed13e52a491d527286ec7.png",
    "asset_09f3cb289325b54b1fa374d447487737.jpg",
    "asset_a2f9cc344b5e2e82fac869512570876a.json",
    "asset_83c633269877cb829d4889a9f0c8c67b.jpg",
    "asset_d6242a29da3b1dbb950d8556347d1cd2.jpg",
    "asset_d61457cdecdbefd65a29d04535e170b0.jpg",
    "asset_3d686070bd10d62c611c0225863af336.jpg",
    "asset_9942588a6c84f959132556d99e83ded6.ttf",
    "asset_b43297391b7d5d5d7b135958668c1876.ttf",
    "asset_f49f3d2d9df5013c9bfaab7e3d39ee57.ttf",
    "asset_466d154fedd98f85c9deb363ccf859a7.ttf",
    "asset_2aec72ba263d6d1a43440a65bfdda36b.ttf",
    "asset_71245b77c6bfd6388e1a2a0e663a4223.ttf",
    "asset_bbdcb5f7a62ab63f26238013e3eb7344.ttf",
    "asset_2d6b814c3234153991cf5e94d02510b0.ttf",
    "asset_21bb70b62317f276f2e97a919ff5bd8c.ttf",
    "asset_778ffc9fe8773a878e9c30a6304784de.png",
    "asset_376d6a4c7f622917c39feb23671ef71d.png",
    "asset_c79c3606a1cf168006ad3979763c7e0c.png",
    "asset_02bc1fa7c0313217bde2d65ccbff40c9.png",
    "asset_35ba0eaec5a4f5ed12ca16fabeae451d.png",
    "asset_b6f15283351698ee72f7a49024daf26f.png",
    "asset_5012d6715ff41a99c9d7ce8c00443383.png",
    "asset_572b3d533ad3769f79d8c768e89ea4ec.png",
    "asset_afd306e6e32d268be777311ae0e93c36.png",
    "asset_05f853df218ba52f7473ddd0e1f599c7.png",
    "asset_09b8877a1869f20b30274c6ba567d5cb.png",
    "asset_0d729b9cd27ec1135d42e7971f7cd887.png",
    "asset_43b8c7986a269052c8e85faec9347abc.png"
  ],
  "currentFullName": "@wingphil/MobileApp",
  "originalFullName": "@wingphil/MobileApp",
  "id": "@wingphil/MobileApp",
  "projectId": "976e6316-33f2-4235-8df6-051d4c17839a",
  "scopeKey": "@wingphil/MobileApp",
  "releaseId": "b6259b2f-14d0-46fa-b7b4-e012498c4aa4",
  "revisionId": "3.0.40-r.0ilAkX_xw",
  "publishedTime": "2021-08-06T11:38:35.157Z",
  "commitTime": "2021-08-06T11:38:35.202Z",
  "bundleUrl": "https://d1wp6m56sqw74a.cloudfront.net/%40wingphil%2FMobileApp%2F3.0.40%2F7d16742c96b25b28bfdd7d384ce41aa6-42.0.0-ios.js",
  "bundleKey": "7d16742c96b25b28bfdd7d384ce41aa6",
  "releaseChannel": "default",
  "hostUri": "exp.host/@wingphil/MobileApp"
}
  platform: "ios"
  buildPhase: "reading manifest"
Aug 6 13:10:12 turtle[77806] ERROR: Error: xcrun exited with non-zero code: 126
    at ChildProcess.completionListener (/users/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_Zoazi_16.6.1/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:514:26)
    at ChildProcess.emit (node:events:394:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at Object.spawnAsync [as default] (/users/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_Zoazi_16.6.1/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at initBuilder (/users/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_Zoazi_16.6.1/lib/node_modules/turtle-cli/src/builders/ios/index.ts:60:21)
    at iosBuilder (/users/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_Zoazi_16.6.1/lib/node_modules/turtle-cli/src/builders/ios/index.ts:24:5)
    at /users/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_Zoazi_16.6.1/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
    at Command.<anonymous> (/users/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_Zoazi_16.6.1/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "ios"
Aug 6 13:10:12 turtle[77806] ERROR: Failed to build standalone app
  err: Error: xcrun exited with non-zero code: 126
      at ChildProcess.completionListener (/users/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_Zoazi_16.6.1/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (node:events:514:26)
      at ChildProcess.emit (node:events:394:28)
      at ChildProcess.emit (node:domain:475:12)
      at maybeClose (node:internal/child_process:1067:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
      ...
      at Object.spawnAsync [as default] (/users/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_Zoazi_16.6.1/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at initBuilder (/users/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_Zoazi_16.6.1/lib/node_modules/turtle-cli/src/builders/ios/index.ts:60:21)
      at iosBuilder (/users/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_Zoazi_16.6.1/lib/node_modules/turtle-cli/src/builders/ios/index.ts:24:5)
      at /users/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_Zoazi_16.6.1/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
      at Command.<anonymous> (/users/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_Zoazi_16.6.1/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "ios"

</pre>
</details>

### Environment

<details>
  <pre> 
Expo CLI 4.9.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.6.1 - /users/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_Zoazi_16.6.1/bin/node
      Yarn: 1.22.11 - /users/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_Zoazi_16.6.1/bin/yarn
      npm: 7.20.3 - /users/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_Zoazi_16.6.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 4.9.1
    Expo Workflow: managed
</pre>
</details>

**Comment by philwingfield** [comment]
It was a permissions thing. I was trying to share a brew installation between users (for fastlane), the user running the build didn't have write permissions to the brew folders and I guess this was the issue. I changed to a local brew installation for the build user and I got a lot further, I am having another issue which I will raise separately if I can't figure it out.
