### ISSUE TITLE
Weird fastlane exited with non-zero code: 1 - (It worked 15 minutes ago and suddenly it does not)

### ISSUE THREAD

**Issue by jaroslavhuss** [expo/turtle#336]
### New Issue Checklist

- [x ] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x ] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.dev](https://docs.expo.dev) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x ] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description
I have built two apps with turtle-cli without any problem. The third app threw an error: 

`Sep 30 19:33:41 turtle[4176] ERROR: Error: fastlane exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    ...
    at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnAsyncThrowError (/@expo/xdl@59.1.0/src/detach/ExponentTools.ts:111:19)
    at runFastlane (/@expo/xdl@59.1.0/src/detach/IosCodeSigning.js:323:9)
    at Object.buildIPA (/@expo/xdl@59.1.0/src/detach/IosCodeSigning.js:132:11)
    at Object.build (/@expo/xdl@59.1.0/src/detach/IosIPABuilder.js:66:28)
    at buildAndSignIPA (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/archive.ts:58:3)
    at Object.buildArchive [as default] (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/archive.ts:20:5)
    at iosBuilder (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/index.ts:33:7)
    at /usr/local/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
    at Command.<anonymous> (/usr/local/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "ios"`

So I came back to those two apps which were working perfectly (15 minutes before the error) - and they throw the same error as well now. 

##### Command executed

sudo EXPO_IOS_DIST_P12_PASSWORD="***************" \
turtle build:ios \
  --team-id ********* \
  --dist-p12-path ./cert.p12 \
  --provisioning-profile-path ./cert.mobileprovision \
  -u ****.***** \
  -p ***********

##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre> Sep 30 19:33:41 turtle[4176] INFO:  	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Sep 30 19:33:41 turtle[4176] INFO:  	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/gym/lib/gym/commands_generator.rb:76:in `run'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Sep 30 19:33:41 turtle[4176] INFO:  	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/gym/lib/gym/commands_generator.rb:16:in `start'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Sep 30 19:33:41 turtle[4176] INFO:  	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Sep 30 19:33:41 turtle[4176] INFO:  	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/bin/fastlane:23:in `<top (required)>'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Sep 30 19:33:41 turtle[4176] INFO:  	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/bin/fastlane:23:in `load'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Sep 30 19:33:41 turtle[4176] INFO:  	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/bin/fastlane:23:in `<main>'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
Sep 30 19:33:41 turtle[4176] INFO:  removed provisioning profile from the home directory
  platform: "ios"
  buildPhase: "building and signing IPA"
Sep 30 19:33:41 turtle[4176] ERROR: Error: fastlane exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    ...
    at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnAsyncThrowError (/@expo/xdl@59.1.0/src/detach/ExponentTools.ts:111:19)
    at runFastlane (/@expo/xdl@59.1.0/src/detach/IosCodeSigning.js:323:9)
    at Object.buildIPA (/@expo/xdl@59.1.0/src/detach/IosCodeSigning.js:132:11)
    at Object.build (/@expo/xdl@59.1.0/src/detach/IosIPABuilder.js:66:28)
    at buildAndSignIPA (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/archive.ts:58:3)
    at Object.buildArchive [as default] (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/archive.ts:20:5)
    at iosBuilder (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/index.ts:33:7)
    at /usr/local/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
    at Command.<anonymous> (/usr/local/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "ios"
Sep 30 19:33:41 turtle[4176] INFO:  delete keychain...
  platform: "ios"
  buildPhase: "deleting keychain"
Sep 30 19:33:41 turtle[4176] INFO:  deleting keychain...
  platform: "ios"
  buildPhase: "deleting keychain"
Sep 30 19:33:42 turtle[4176] INFO:  done deleting keychain
  platform: "ios"
  buildPhase: "deleting keychain"
Sep 30 19:33:42 turtle[4176] ERROR: Failed to build standalone app
  err: Error: fastlane exited with non-zero code: 1
      at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:422:26)
      at ChildProcess.emit (events.js:315:20)
      at ChildProcess.EventEmitter.emit (domain.js:467:12)
      at maybeClose (internal/child_process.js:1048:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
      ...
      at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at spawnAsyncThrowError (/@expo/xdl@59.1.0/src/detach/ExponentTools.ts:111:19)
      at runFastlane (/@expo/xdl@59.1.0/src/detach/IosCodeSigning.js:323:9)
      at Object.buildIPA (/@expo/xdl@59.1.0/src/detach/IosCodeSigning.js:132:11)
      at Object.build (/@expo/xdl@59.1.0/src/detach/IosIPABuilder.js:66:28)
      at buildAndSignIPA (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/archive.ts:58:3)
      at Object.buildArchive [as default] (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/archive.ts:20:5)
      at iosBuilder (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/index.ts:33:7)
      at /usr/local/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
      at Command.<anonymous> (/usr/local/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "ios"</pre>
</details>

### Environment

<details>
  <pre>  Expo CLI 4.12.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.24.1 - /usr/local/bin/npm
      Watchman: 2021.09.27.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: * => 38.0.8 
      react: * => 16.11.0 
      react-dom: * => 16.11.0 
      react-native: * => 0.62.2 
      react-native-web: * => 0.11.7 
    npmGlobalPackages:
      expo-cli: 4.12.0
    Expo Workflow: managed </pre>
</details>

**Comment by DarkVito** [comment]
Hey i have the same problem. Have you solved it?
