### ISSUE TITLE
Failed to build android app on turtle 0.22.5 and 0.21.9-alpha.4

### ISSUE THREAD

**Issue by canhlocphan** [expo/turtle#345]
Hi everyone, pls help me when use turtle-cli to build apk from expo project
I got stuck trying to build out apk file using turtle-cli with version 0.22.5 and 0.21.9-alpha.4 both failed after starting build
turtle[38621] WARN:  Failed to check for turtle-cli update. Currently I use SDK: 41.0.1 and tried deleting : ~/.turtle/workingdir but the problem is still the same
  err: Error: Unable to read /home/ubuntu/.cache/expo/turtle-cli-updates.json. SyntaxError: Unexpected end of JSON input      at Cacher.getAsync (/@expo/xdl@59.1.0/src/tools/FsCache.ts:109:15)
      at Object.checkAsync (/@expo/xdl@59.1.0/src/tools/ModuleVersion.ts:23:43)
      at checkForUpdateAsync (/usr/lib/node_modules/turtle-cli/src/bin/index.ts:62:50)
      at Command.<anonymous> (/usr/lib/node_modules/turtle-cli/src/bin/index.ts:19:7)
  platform: "android"
![image](https://user-images.githubusercontent.com/83717651/136802744-c44c3ade-d308-42ce-ba98-b7987c886bd0.png)
  ==========================
  and after it's done
  ==========================
turtle[39972] ERROR: Error: ./gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
    ...
    at spawnAsync (/usr/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnAsyncThrowError (/@expo/xdl@59.1.0/src/detach/ExponentTools.ts:111:19)
    at buildShellAppAsync (/@expo/xdl@59.1.0/src/detach/AndroidShellApp.js:1476:11)
    at Object.createAndroidShellAppAsync (/@expo/xdl@59.1.0/src/detach/AndroidShellApp.js:380:5)
    at runShellAppBuilder (/usr/lib/node_modules/turtle-cli/src/builders/android.ts:91:5)
    at buildAndroid (/usr/lib/node_modules/turtle-cli/src/builders/android.ts:23:26)
    at /usr/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
    at Command.<anonymous> (/usr/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "android"
Oct 11 13:37:07 turtle[39972] ERROR: Failed to build standalone app
  err: Error: ./gradlew exited with non-zero code: 1
      at ChildProcess.completionListener (/usr/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:520:26)
      at ChildProcess.emit (events.js:400:28)
      at ChildProcess.emit (domain.js:475:12)
      at maybeClose (internal/child_process.js:1058:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
      ...
      at spawnAsync (/usr/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at spawnAsyncThrowError (/@expo/xdl@59.1.0/src/detach/ExponentTools.ts:111:19)
      at buildShellAppAsync (/@expo/xdl@59.1.0/src/detach/AndroidShellApp.js:1476:11)
      at Object.createAndroidShellAppAsync (/@expo/xdl@59.1.0/src/detach/AndroidShellApp.js:380:5)
      at runShellAppBuilder (/usr/lib/node_modules/turtle-cli/src/builders/android.ts:91:5)
      at buildAndroid (/usr/lib/node_modules/turtle-cli/src/builders/android.ts:23:26)
      at /usr/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
      at Command.<anonymous> (/usr/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "android"
![image](https://user-images.githubusercontent.com/83717651/136802798-6c583fc6-0152-46be-abce-a633d9e4bca7.png)
============================

**Comment by wkozyra95** [comment]
try deleting `~/.cache/expo` and `~/.turtle`
