### ISSUE TITLE
iOS build success in expo cloud but not in turtle-cli

### ISSUE THREAD

**Issue by benhurott** [expo/turtle#35]
I'm trying to build the ios application using the `turtle-cli` tool.
It works properly with `exp build:ios --clear-credentials --clear-app-credentials --clear-dist-cert --release-channel my-channel` and providing all the info.

If I try to use the same info in `turtle build:ios` it is showing me this error:

```
Apr 4 09:51:40 turtle[5899] ERROR: Error: Process exited with non-zero code: 1
    at ChildProcess.child.on (/Users/ben/.nvm/versions/node/v10.14.1/lib/node_modules/turtle-cli/node_modules/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:39:21)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Pipe._handle.close (net.js:606:12)
  platform: "ios"
  environment: null
```

Here is the command I'm running:
```
EXPO_IOS_DIST_P12_PASSWORD=******** sh turtle-build.sh
```

Here is the `turtle-build.sh`:
```bash
turtle build:ios \
  --username "********" \
  --password "********" \
  --release-channel "my-channel" \
  --team-id "P********5" \
  --dist-p12-path "******/ios_certificates/ios_distribution.p12" \
  --provisioning-profile-path "******/ios_certificates/appstore.mobileprovision"
```

Env info:
Xcode: Version 10.2 (10E125) (Command Line Tools is the same)
Node: v10.14.1

**Comment by dsokal** [comment]
Hello @benhurott,

1. Please don't use `exp`, it's deprecated. Use `expo-cli` instead - you can install it with `yarn global add expo-cli`.
2. Please send more logs from `turtle build:ios`, the error you posted is too generic and it doesn't really say anything. I wonder what logs you're getting before that error.

Thanks for reporting!

**Comment by benhurott** [comment]
Hey @dsokal sorry for the delay =/

Here is some more info:
```
Apr 10 15:02:27 turtle[12217] INFO:  	from /Users/ben/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  platform: "ios"
  environment: null
  buildPhase: "building and signing IPA"
  source: "stdout"
Apr 10 15:02:27 turtle[12217] INFO:  	from /Users/ben/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/gym/lib/gym/commands_generator.rb:75:in `run'
  platform: "ios"
  environment: null
  buildPhase: "building and signing IPA"
  source: "stdout"
Apr 10 15:02:27 turtle[12217] INFO:  	from /Users/ben/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/gym/lib/gym/commands_generator.rb:15:in `start'
  platform: "ios"
  environment: null
  buildPhase: "building and signing IPA"
  source: "stdout"
Apr 10 15:02:27 turtle[12217] INFO:  	from /Users/ben/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
  platform: "ios"
  environment: null
  buildPhase: "building and signing IPA"
  source: "stdout"
Apr 10 15:02:27 turtle[12217] INFO:  	from /Users/ben/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.116.1/bin/fastlane:23:in `<top (required)>'
  platform: "ios"
  environment: null
  buildPhase: "building and signing IPA"
  source: "stdout"
Apr 10 15:02:27 turtle[12217] INFO:  	from /Users/ben/.fastlane/bin/bundle/bin/fastlane:22:in `load'
  platform: "ios"
  environment: null
  buildPhase: "building and signing IPA"
  source: "stdout"
Apr 10 15:02:27 turtle[12217] INFO:  	from /Users/ben/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
  platform: "ios"
  environment: null
  buildPhase: "building and signing IPA"
  source: "stdout"
Apr 10 15:02:27 turtle[12217] INFO:  removed provisioning profile from the home directory
  platform: "ios"
  environment: null
  buildPhase: "building and signing IPA"
Apr 10 15:02:27 turtle[12217] ERROR: Error: Process exited with non-zero code: 1
    at ChildProcess.child.on (/Users/ben/.nvm/versions/node/v10.14.1/lib/node_modules/turtle-cli/node_modules/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:39:21)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Pipe._handle.close (net.js:606:12)
  platform: "ios"
  environment: null
Apr 10 15:02:27 turtle[12217] INFO:  delete keychain...
  platform: "ios"
  environment: null
  buildPhase: "deleting keychain"
Apr 10 15:02:27 turtle[12217] INFO:  deleting keychain...
  platform: "ios"
  environment: null
  buildPhase: "deleting keychain"
Apr 10 15:02:31 turtle[12217] INFO:  done deleting keychain
  platform: "ios"
  environment: null
  buildPhase: "deleting keychain"
Apr 10 15:02:31 turtle[12217] ERROR: Failed to build standalone app: Process exited with non-zero code: 1
  platform: "ios"
  environment: null
Apr 10 15:02:31 turtle[12217] ERROR: Error: Process exited with non-zero code: 1
    at ChildProcess.child.on (/Users/ben/.nvm/versions/node/v10.14.1/lib/node_modules/turtle-cli/node_modules/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:39:21)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Pipe._handle.close (net.js:606:12)
  platform: "ios"
  environment: null
```

is it enough? Tell me if you need more.

**Comment by dsokal** [comment]
Turtle CLI doesn't need your Push Notifications certificate/key because it's not necessary for building the .ipa file. If you wish to use **Expo** Push Notifications module you need to provide Expo servers with that thing. Unfortunately, the only way right now to upload iOS push notifications credentials to Expo servers is to run `expo build:ios` at least once. We hope to change that soon. Sorry for the inconvenience!

Regarding your original problem - you still didn't send any useful logs. The most interesting part is the fastlane stacktrace (and few lines before that). If you don't want to share the whole log file here, you can find me on Expo Developers Slack (@dsokal) and DM me with the logs file.

**Comment by benhurott** [comment]
Ok goit it.
We tried to use the turtle to generate the ipa and submit to the qa team.
But if it's not the purpose, I will close this issue.
Thanks.
