### ISSUE TITLE
Exception while trying to build Android app. Expo SDK version 42, turtle version 0.23.1

### ISSUE THREAD

**Issue by zgordon02** [expo/turtle#351]
### New Issue Checklist

- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.dev](https://docs.expo.dev) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x] **I enclosed the complete output when running turtle, including the stack trace and command used.**

##### Command executed

```
EXPO_ANDROID_KEY_PASSWORD=some_pass EXPO_ANDROID_KEYSTORE_PASSWORD=some_pass turtle build:android --keystore-path ./some_keystore.keystore --keystore-alias alias --public-url https://aws_public_url/android-index.json -t apk -m debug
```
##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre> Oct 27 16:26:41 turtle[56901] INFO:  shell app for SDK 42.0.0 doesn't exist, downloading...
  platform: "android"
  buildPhase: "setting up environment"
downloading [=========           ] 45% 1.2sOct 27 16:26:43 turtle[56901] INFO:  shell app has been downloaded
  platform: "android"
  buildPhase: "setting up environment"
Oct 27 16:26:43 turtle[56901] INFO:  extracting shell app (this may take a while)...
  platform: "android"
  buildPhase: "setting up environment"
Oct 27 16:27:49 turtle[56901] INFO:  shell app extracted
  platform: "android"
  buildPhase: "setting up environment"
Oct 27 16:27:49 turtle[56901] INFO:  installing dependencies in /Users/zgordon/.turtle/workingdir/android/sdk42 directory...
  platform: "android"
  buildPhase: "setting up environment"
Oct 27 16:28:27 turtle[56901] INFO:  npm WARN EBADENGINE Unsupported engine {
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:27 turtle[56901] INFO:  npm WARN EBADENGINE   package: 'minifier@0.7.1',
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:27 turtle[56901] INFO:  npm 
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:27 turtle[56901] INFO:  WARN EBADENGINE   required: { node: '~0.10.0 || ^0.12.0' },
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:27 turtle[56901] INFO:  npm WARN EBADENGINE   current: { node: 'v16.9.1', npm: '7.24.0' }
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:27 turtle[56901] INFO:  npm WARN EBADENGINE }
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:35 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:35 turtle[56901] INFO:   WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:35 turtle[56901] INFO:  npm WARN
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:35 turtle[56901] INFO:   deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:35 turtle[56901] INFO:  npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:35 turtle[56901] INFO:  npm WARN 
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:35 turtle[56901] INFO:  deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:36 turtle[56901] INFO:  npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:36 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:36 turtle[56901] INFO:   WARN deprecated har-validator@5.1.5: this library is no longer supported
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:36 turtle[56901] INFO:  npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:36 turtle[56901] INFO:  npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:36 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:36 turtle[56901] INFO:   WARN deprecated minifier@0.7.1: please don't use. see readme (https://github.com/fizker/minifier) for details
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:36 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:36 turtle[56901] INFO:   WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:   WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:   WARN deprecated uuid@3.0.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:   WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:   WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:   WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:   WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:   WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:  npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:  npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:  npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:   WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:  npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:  npm WARN deprecated
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:   uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:  npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:  npm 
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:37 turtle[56901] INFO:  WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:38 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:38 turtle[56901] INFO:   WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:38 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:38 turtle[56901] INFO:   WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:39 turtle[56901] INFO:  npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:39 turtle[56901] INFO:  npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:41 turtle[56901] INFO:  npm WARN deprecated core-js@1.2.7: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:42 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:42 turtle[56901] INFO:   WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:42 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:42 turtle[56901] INFO:   WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:42 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:42 turtle[56901] INFO:   WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:42 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:42 turtle[56901] INFO:   WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:42 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:42 turtle[56901] INFO:   WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:44 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:44 turtle[56901] INFO:   WARN deprecated processing-js@1.6.6: This project has been archived. Please use p5js instead.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:   ERR! code 1
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm ERR! path /Users/zgordon/.turtle/workingdir/android/sdk42/packages/expo-apple-authentication
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:   ERR! command failed
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm ERR! command sh -c expo-module prepare
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm ERR! /Users/zgordon/.turtle/workingdir/android/sdk42/node_modules/commander/index.js:837
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm ERR!         throw new Error(executableMissing);
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm ERR!
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:           ^
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm ERR! 
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm ERR! Error: 'expo-module-prepare' does not exist
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm ERR!  - if 'prepare' is not meant to be an executable command, remove description parameter from '.command()' and use '.description()' instead
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm ERR!  - if the default executable name is not suitable, use the executableFile option to supply a custom name
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm ERR!     at ChildProcess.<anonymous> (/Users/zgordon/.turtle/workingdir/android/sdk42/node_modules/commander/index.js:837:15)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm ERR!     at ChildProcess.emit (node:events:394:28)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm ERR!     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm ERR!     at onErrorNT (node:internal/child_process:477:16)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm ERR! A complete log of this run can be found in:
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] INFO:  npm ERR!     /Users/zgordon/.npm/_logs/2021-10-27T21_28_57_638Z-debug.log
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Oct 27 16:28:57 turtle[56901] ERROR: Failed to build standalone app
  err: Error: npm exited with non-zero code: 1
      at ChildProcess.completionListener (/Users/zgordon/.nvm/versions/node/v16.9.1/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (node:events:514:26)
      at ChildProcess.emit (node:events:394:28)
      at ChildProcess.emit (node:domain:475:12)
      at maybeClose (node:internal/child_process:1064:16)
      at Socket.<anonymous> (node:internal/child_process:450:11)
      at Socket.emit (node:events:394:28)
      at Socket.emit (node:domain:475:12)
      at Pipe.<anonymous> (node:net:672:12)
      ...
      at spawnAsync (/Users/zgordon/.nvm/versions/node/v16.9.1/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (/@expo/xdl@59.1.7/src/detach/ExponentTools.ts:111:19)
      at _installNodeModules (/Users/zgordon/.nvm/versions/node/v16.9.1/lib/node_modules/turtle-cli/src/bin/setup/android/index.ts:106:23)
      at _shellAppPostDownloadAction (/Users/zgordon/.nvm/versions/node/v16.9.1/lib/node_modules/turtle-cli/src/bin/setup/android/index.ts:91:5)
      at Object.ensureShellAppIsPresent (/Users/zgordon/.nvm/versions/node/v16.9.1/lib/node_modules/turtle-cli/src/bin/setup/utils/common.ts:40:5)
      at Object.setup [as default] (/Users/zgordon/.nvm/versions/node/v16.9.1/lib/node_modules/turtle-cli/src/bin/setup/android/index.ts:60:5)
      at Object.setup [as default] (/Users/zgordon/.nvm/versions/node/v16.9.1/lib/node_modules/turtle-cli/src/bin/setup/setup.ts:15:12)
      at /Users/zgordon/.nvm/versions/node/v16.9.1/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:79:7
      at Command.<anonymous> (/Users/zgordon/.nvm/versions/node/v16.9.1/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "android" </pre>
</details>

### Environment

<details>
  <pre>  Expo CLI 4.12.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
      npm: 7.24.0 - ~/.nvm/versions/node/v16.9.1/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 30, 31
        Build Tools: 31.0.0
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.12.0
    Expo Workflow: managed
 </pre>
</details>

Any help is appreciated! I'm trying to build a debug apk and have no luck

**Comment by negamaxi** [comment]
Faced the same issue on macOS build machine:

<details>

![Снимок экрана от 2021-11-08 11-02-16](https://user-images.githubusercontent.com/16529171/140705182-95610194-457c-4bb0-9746-bbf9f32a29b8.png)

</details>

turtle 0.23.3
Expo 42
openjdk version "1.8.0_292"

On Linux machine error doesn't show up and build succsesfully completes.

**Comment by MaulikRajpara97** [comment]
I have faced similar issue on my mac as well .
Any help would be appreciated

**Comment by buddebej** [comment]
+1 On Linux

**Comment by farajfarook** [comment]
+1 on Linux. Did anyone found a solution for this issue?

**Comment by MaulikRajpara97** [comment]
utilize yarn instead of npm for the setup and build processes to work.

You may find a working gitlab-ci.yml configuration 
https://gitlab.com/Gr3at/expo-ci/-/blob/4f861a9c812f4b1027b0f711f8a261e4bad1bb91/.gitlab-ci.yml

**Comment by farajfarook** [comment]
> utilize yarn instead of npm for the setup and build processes to work.
> 
> You may find a working gitlab-ci.yml configuration https://gitlab.com/Gr3at/expo-ci/-/blob/4f861a9c812f4b1027b0f711f8a261e4bad1bb91/.gitlab-ci.yml

Npm was the culprit. I got it working with node 16 and yarn 2. Thanks for your help.
