### ISSUE TITLE
turtle-cli build resulting in Error: Failed to build standalone app after node 16.13

### ISSUE THREAD

**Issue by trajano** [expo/turtle#367]
### New Issue Checklist

- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read [docs.expo.dev](https://docs.expo.dev) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description

Just changed my node version to 16.13.0 from 14.18.1 and the android aab fails.

##### Command executed

```sh
turtle build:android \
          --keystore-path $(keystore.secureFilePath) \
          --keystore-alias $(keyAlias) \
          -t aab \
          --release-channel ${{ parameters.env }} \
          -o $(Build.ArtifactStagingDirectory)/app.aab
```
##### Complete output when running turtle, including the stack trace and command used

<details>

```txt
2021-12-09T01:31:27.1580801Z ##[section]Starting: aab
2021-12-09T01:31:27.1588247Z ==============================================================================
2021-12-09T01:31:27.1588599Z Task         : Bash
2021-12-09T01:31:27.1588925Z Description  : Run a Bash script on macOS, Linux, or Windows
2021-12-09T01:31:27.1589222Z Version      : 3.189.0
2021-12-09T01:31:27.1589509Z Author       : Microsoft Corporation
2021-12-09T01:31:27.1589884Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
2021-12-09T01:31:27.1590316Z ==============================================================================
2021-12-09T01:31:28.1461555Z Generating script.
2021-12-09T01:31:28.1464455Z ========================== Starting Command Output ===========================
2021-12-09T01:31:28.1470561Z [command]/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/85b7c84a-7b5a-43b2-812c-03a6ac942262.sh
2021-12-09T01:31:31.2916310Z Dec 9 01:31:31 turtle[3401] INFO:  [32mshell app for SDK 42.0.0 doesn't exist, downloading...[39m
2021-12-09T01:31:31.2918054Z [32m  platform: "android"[39m
2021-12-09T01:31:31.2918938Z [32m  buildPhase: "setting up environment"[39m
2021-12-09T01:31:32.3648322Z Dec 9 01:31:32 turtle[3401] INFO:  [32mshell app has been downloaded[39m
2021-12-09T01:31:32.3649155Z [32m  platform: "android"[39m
2021-12-09T01:31:32.3649764Z [32m  buildPhase: "setting up environment"[39m
2021-12-09T01:31:32.3667750Z Dec 9 01:31:32 turtle[3401] INFO:  [32mextracting shell app (this may take a while)...[39m
2021-12-09T01:31:32.3669896Z [32m  platform: "android"[39m
2021-12-09T01:31:32.3670609Z [32m  buildPhase: "setting up environment"[39m
2021-12-09T01:32:57.9102411Z Dec 9 01:32:57 turtle[3401] INFO:  [32mshell app extracted[39m
2021-12-09T01:32:57.9104389Z [32m  platform: "android"[39m
2021-12-09T01:32:57.9105646Z [32m  buildPhase: "setting up environment"[39m
2021-12-09T01:32:57.9108249Z Dec 9 01:32:57 turtle[3401] INFO:  [32minstalling dependencies in /home/vsts/.turtle/workingdir/android/sdk42 directory...[39m
2021-12-09T01:32:57.9109327Z [32m  platform: "android"[39m
2021-12-09T01:32:57.9110646Z [32m  buildPhase: "setting up environment"[39m
2021-12-09T01:32:58.2478412Z Dec 9 01:32:58 turtle[3401] INFO:  [32myarn install v1.22.17[39m
2021-12-09T01:32:58.2479650Z [32m  platform: "android"[39m
2021-12-09T01:32:58.2480541Z [32m  buildPhase: "setting up environment"[39m
2021-12-09T01:32:58.2481341Z [32m  source: "stdout"[39m
2021-12-09T01:32:58.2806759Z Dec 9 01:32:58 turtle[3401] INFO:  [32minfo No lockfile found.[39m
2021-12-09T01:32:58.2807997Z [32m  platform: "android"[39m
2021-12-09T01:32:58.2808883Z [32m  buildPhase: "setting up environment"[39m
2021-12-09T01:32:58.2809814Z [32m  source: "stdout"[39m
2021-12-09T01:32:58.4296763Z Dec 9 01:32:58 turtle[3401] INFO:  [32m[1/4] Resolving packages...[39m
2021-12-09T01:32:58.4298135Z [32m  platform: "android"[39m
2021-12-09T01:32:58.4299020Z [32m  buildPhase: "setting up environment"[39m
2021-12-09T01:32:58.4299863Z [32m  source: "stdout"[39m
2021-12-09T01:32:58.6173972Z Dec 9 01:32:58 turtle[3401] INFO:  [32merror Couldn't find package "react-native" on the "npm" registry.[39m
2021-12-09T01:32:58.6175479Z [32m  platform: "android"[39m
2021-12-09T01:32:58.6176556Z [32m  buildPhase: "setting up environment"[39m
2021-12-09T01:32:58.6177529Z [32m  source: "stderr"[39m
2021-12-09T01:32:58.6179012Z Dec 9 01:32:58 turtle[3401] INFO:  [32minfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.[39m
2021-12-09T01:32:58.6180288Z [32m  platform: "android"[39m
2021-12-09T01:32:58.6181316Z [32m  buildPhase: "setting up environment"[39m
2021-12-09T01:32:58.6182273Z [32m  source: "stdout"[39m
2021-12-09T01:32:58.6350163Z Dec 9 01:32:58 turtle[3401] ERROR: [31mFailed to build standalone app[39m
2021-12-09T01:32:58.6351092Z [31m  err: Error: yarn exited with non-zero code: 1[39m
2021-12-09T01:32:58.6352120Z [31m      at ChildProcess.completionListener (/home/vsts/work/1/.nvm/versions/node/v16.13.0/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)[39m
2021-12-09T01:32:58.6353353Z [31m      at Object.onceWrapper (node:events:510:26)[39m
2021-12-09T01:32:58.6354252Z [31m      at ChildProcess.emit (node:events:390:28)[39m
2021-12-09T01:32:58.6354927Z [31m      at ChildProcess.emit (node:domain:475:12)[39m
2021-12-09T01:32:58.6355642Z [31m      at maybeClose (node:internal/child_process:1064:16)[39m
2021-12-09T01:32:58.6356443Z [31m      at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)[39m
2021-12-09T01:32:58.6357060Z [31m      ...[39m
2021-12-09T01:32:58.6357896Z [31m      at spawnAsync (/home/vsts/work/1/.nvm/versions/node/v16.13.0/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)[39m
2021-12-09T01:32:58.6358839Z [31m      at Object.spawnAsyncThrowError (/@expo/xdl@59.1.7/src/detach/ExponentTools.ts:111:19)[39m
2021-12-09T01:32:58.6359816Z [31m      at _installNodeModules (/home/vsts/work/1/.nvm/versions/node/v16.13.0/lib/node_modules/turtle-cli/src/bin/setup/android/index.ts:106:23)[39m
2021-12-09T01:32:58.6360878Z [31m      at _shellAppPostDownloadAction (/home/vsts/work/1/.nvm/versions/node/v16.13.0/lib/node_modules/turtle-cli/src/bin/setup/android/index.ts:91:5)[39m
2021-12-09T01:32:58.6361946Z [31m      at Object.ensureShellAppIsPresent (/home/vsts/work/1/.nvm/versions/node/v16.13.0/lib/node_modules/turtle-cli/src/bin/setup/utils/common.ts:40:5)[39m
2021-12-09T01:32:58.6363020Z [31m      at Object.setup [as default] (/home/vsts/work/1/.nvm/versions/node/v16.13.0/lib/node_modules/turtle-cli/src/bin/setup/android/index.ts:60:5)[39m
2021-12-09T01:32:58.6364072Z [31m      at Object.setup [as default] (/home/vsts/work/1/.nvm/versions/node/v16.13.0/lib/node_modules/turtle-cli/src/bin/setup/setup.ts:15:12)[39m
2021-12-09T01:32:58.6365199Z [31m      at /home/vsts/work/1/.nvm/versions/node/v16.13.0/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:79:7[39m
2021-12-09T01:32:58.6366165Z [31m      at Command.<anonymous> (/home/vsts/work/1/.nvm/versions/node/v16.13.0/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)[39m
2021-12-09T01:32:58.6366913Z [31m  platform: "android"[39m
2021-12-09T01:32:58.6688160Z ##[error]Bash exited with code '1'.
2021-12-09T01:32:58.6725124Z ##[section]Finishing: aab
```

</details>

### Environment

I am not using `yarn` in my app (there's only `package-lock.json`

<details>

```
 Expo CLI 4.13.0 environment info:
    System:
      OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.13.0 - ~/work/1/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.0 - ~/work/1/.nvm/versions/node/v16.13.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 27, 28, 29, 30, 31
        Build Tools: 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0
        Android NDK: 21.4.7075529
    npmPackages:
      expo: ^42.0.0 => 42.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

```

</details>

**Comment by brentvatne** [comment]
> Couldn't find package "react-native" on the "npm" registry

this looks like a problem with npm or possibly with a npm proxy that you're using

**Comment by trajano** [comment]
Appears to be a network connectivity issue.  I just restarted an hour later and it worked again.
