### ISSUE TITLE
React Native Failed Building Expo APK using Turtle CLI

### ISSUE THREAD

**Issue by ahmad-dawood** [expo/turtle#373]
I am trying to build a local apk by React native Expo project using turtle CLI on windows 10, after installing all prerquisites including Java version 8 ,bash,Node 16,Expo CLI latest version and configuring Environment variables and path for JAVA

After running this command :
**_turtle setup:android_** 

 i receive this Error Log:
-in some help for same issues on github,i tried installing Java 8 from the official site and also tried to install it manually,installed 64bit then 32bit for the same version 8 

**Note:** 
-I dont have Android Studio installed
-No other Java versions installed,

all gave me this error in the log :

**_ERROR: Failed to setup environment for android builds
  err: Error: ./configureAndroidSdk.sh exited with non-zero code: 127**_**
 

`
Dec 31 09:51:53 turtle[9724] ERROR: Failed to setup environment for android builds
  err: Error: ./configureAndroidSdk.sh exited with non-zero code: 127
      at ChildProcess.completionListener (C:\Users\ahmad\AppData\Roaming\npm\node_modules\turtle-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
      at Object.onceWrapper (node:events:510:26)
      at ChildProcess.emit (node:events:390:28)
      at ChildProcess.emit (node:domain:475:12)
      at ChildProcess.cp.emit (C:\Users\ahmad\AppData\Roaming\npm\node_modules\turtle-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
      at maybeClose (node:internal/child_process:1064:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
      ...
      at spawnAsync (C:\Users\ahmad\AppData\Roaming\npm\node_modules\turtle-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
      at Object.spawnAsyncThrowError (C:\@expo\xdl@59.1.7\src\detach\ExponentTools.ts:111:19)
      at _configureSdk (C:\Users\ahmad\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\setup\android\sdk.ts:54:23)
      at Object.ensureAndroidSDKIsPresent [as default] (C:\Users\ahmad\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\setup\android\sdk.ts:34:7)
      at prepareAndroidEnv (C:\Users\ahmad\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\setup\android\index.ts:70:21)
      at Object.setup [as default] (C:\Users\ahmad\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\setup\android\index.ts:58:3)
      at Object.setup [as default] (C:\Users\ahmad\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\setup\setup.ts:15:12)
      at setupAction (C:\Users\ahmad\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\commands\setup.ts:33:5)
      at C:\Users\ahmad\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\commands\setup.ts:22:40
      at Command.<anonymous> (C:\Users\ahmad\AppData\Roaming\npm\node_modules\turtle-cli\src\bin\index.ts:23:12)
  platform: "android"
`

**Comment by wkozyra95** [comment]
turtle-cli is not supported on windows(it might work under WSL)
