### ISSUE TITLE
Failed to save icon file to disk. 

### ISSUE THREAD

**Issue by kermit-sad-frog** [expo/turtle#376]
### New Issue Checklist

- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.dev](https://docs.expo.dev) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description

when execute 
```
EXPO_ANDROID_KEYSTORE_PASSWORD=... \
EXPO_ANDROID_KEY_PASSWORD=.... \
turtle build:android \
  --type apk \
  --keystore-path ./keystore.jks \
  --keystore-alias "keyalias" \
  --allow-non-https-public-url \
  --public-url http://127.0.0.1:8000/android-index.json
  ```
  
  i receive such error:
  ```/@expo/xdl@59.1.7/src/detach/AndroidIcons.ts:62
    throw new Error(`Failed to save icon file to disk. (${e})`);
          ^
Error: Failed to save icon file to disk. (TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined)
    at _resizeIconsAsync (/@expo/xdl@59.1.7/src/detach/AndroidIcons.ts:62:11)
    at creat
    ```

##### Command executed

```
EXPO_ANDROID_KEYSTORE_PASSWORD=... \
EXPO_ANDROID_KEY_PASSWORD=.... \
turtle build:android \
  --type apk \
  --keystore-path ./keystore.jks \
  --keystore-alias "keyalias" \
  --allow-non-https-public-url \
  --public-url http://127.0.0.1:8000/android-index.json
  ```
##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre> EXPO_ANDROID_KEYSTORE_PASSWORD=... \
EXPO_ANDROID_KEY_PASSWORD=.... \
turtle build:android \
  --type apk \
  --keystore-path ./keystore.jks \
  --keystore-alias "keyalias" \
  --allow-non-https-public-url \
  --public-url http://127.0.0.1:8000/android-index.json
Jan 6 22:00:52 turtle[48952] WARN:  Skipping NDK installation
  platform: "android"
  buildPhase: "setting up environment"
Jan 6 22:00:52 turtle[48952] INFO:  Using manifest: {
  "android": {
    "package": "com.iwd",
    "adaptiveIcon": {
      "backgroundColor": "#FFFFFF"
    },
    "permissions": [
      "CAMERA",
      "WRITE_EXTERNAL_STORAGE",
      "READ_EXTERNAL_STORAGE",
      "CAMERA_ROLL"
    ],
    "versionCode": 20
  },
  "androidNavigationBar": {
    "barStyle": "light-content"
  },
  "name": "bar",
  "slug": "bar",
  "version": "1.0.0",
  "sdkVersion": "44.0.0",
  "platforms": [
    "ios",
    "android",
    "web"
  ],
  "currentFullName": "@glabz/bar",
  "originalFullName": "@glabz/bar",
  "locales": {},
  "bundledAssets": [
    "asset_c00b5b51f0fd354e216f319a78fb252a.png",
    "asset_ae0fcc2b007ded72c6f985671da3338e.png",
    "asset_46d1173c53d96832e868151c1648ea42.png",
    "asset_34d53ae6f3c2303163010aef6efe27ba.png",
    "asset_a610d434605f8a50094a4029a0ea5ff6.png",
    "asset_672c933f8123dda6d0e731c58bd5f4e1.json",
    "asset_6d960622b5d2bdcd2e757ea77d8cd4ea.json",
    "asset_d260a261f41d93b96bdfc1ab7323f29b.json",
    "asset_fb82932703831c5aed5d19b4f66aa1d2.json",
    "asset_9463423d717b1c2a8558909ead75ba09.json",
    "asset_9f05530c64a774d02410e02d0d1554f3.json",
    "asset_2dd3a3e61fb252e9dcb6af9e6aec37ab.json",
    "asset_bcc034acc51c5c8f92c257a28ec9a1d6.json",
    "asset_23bfef5a2cc986befc66df420cb56889.json",
    "asset_2ac32dec71143dccca808a592a85eb9f.json",
    "asset_59e1d07580be5bc3c66af78930b04b98.json",
    "asset_3a2ba31570920eeb9b1d217cabe58315.ttf",
    "asset_8b12b3e16d591abc926165fa8f760e3b.json",
    "asset_744ce60078c17d86006dd0edabcd59a7.ttf",
    "asset_461d9bba8b6a3c91675039df12cfe6ca.json",
    "asset_140c53a7643ea949007aa9a282153849.ttf",
    "asset_94c4ffdcbffeb0570c635d7f8edd8a25.json",
    "asset_e766963327e0a89f9ec2ba88646b6177.ttf",
    "asset_83d0d0700e24da7297be10ae931dd38f.json",
    "asset_b49ae8ab2dbccb02c4d11caaacf09eab.ttf",
    "asset_39843e5d52a6c5c42d5abdb0b34bcaa6.json",
    "asset_b06871f281fee6b241d60582ae9369b9.ttf",
    "asset_f1f91feb805137c9283fb766620ec5eb.json",
    "asset_276ee4e65ded9a91cfe0be813e95e42d.json",
    "asset_8d09f2281ac9c99f438fb1c0b5c66d20.json",
    "asset_db78b9359171f24936b16d84f63af378.ttf",
    "asset_1ab236ed440ee51810c56bd16628aef0.ttf",
    "asset_13685372945d816a2b474fc082fd9aaa.ttf",
    "asset_e20945d7c929279ef7a6f1db184a4470.ttf",
    "asset_60668d999bbaf663420340f7bdd580d7.json",
    "asset_b3263095df30cb7db78c613e73f9499a.ttf",
    "asset_bb0e1479c256e29e7ee92433a5e4b43e.json",
    "asset_6a2ddad1092a0a1c326b6d0e738e682b.ttf",
    "asset_f337aab857fd04843f0a882ec5726fb3.json",
    "asset_8ef52a15e44481b41e7db3c7eaf9bb83.ttf",
    "asset_fdbedb7e67aa7c0ecad83d9c2fa4dfba.json",
    "asset_8e7f807ef943bff1f6d3c2c6e0f3769e.ttf",
    "asset_fdc01171a7a7ea76b187afcd162dee7d.json",
    "asset_d2285965fe34b05465047401b8595dd0.ttf",
    "asset_647543ebfccf6e5495434383598453d1.json",
    "asset_5cdf883b18a5651a29a4d1ef276d2457.ttf",
    "asset_74d124a3caeac2bea111f3ca2f2dd34a.json",
    "asset_a970ccb3cd9a0d56fb2e49159999d02f.json"
  ],
  "assetUrlOverride": "./assets",
  "publishedTime": "2022-01-06T19:59:37.473Z",
  "commitTime": "2022-01-06T19:59:37.473Z",
  "releaseId": "bbf7fc3b-6289-4992-80cd-1a2a137431bf",
  "revisionId": "mLQVbNkdGd",
  "developer": {
    "tool": "exp"
  },
  "id": "@glabz/bar",
  "platform": "android",
  "bundleUrl": "http://127.0.0.1:8000/bundles/android-78239b2132d26da1beeb77c52b55e10a.js",
  "dependencies": [
    "@expo/vector-icons",
    "@types/styled-components",
    "expo",
    "expo-asset",
    "expo-barcode-scanner",
    "expo-file-system",
    "expo-sqlite",
    "native-base",
    "react",
    "react-dom",
    "react-native",
    "react-native-safe-area-context",
    "react-native-svg",
    "react-native-web",
    "react-redux",
    "react-router-native",
    "redux",
    "simplify-redux-app",
    "styled-components"
  ]
}
  platform: "android"
  buildPhase: "reading manifest"
Jan 6 22:00:52 turtle[48952] INFO:  Starting build process
  platform: "android"
  buildPhase: "starting builder"
Jan 6 22:00:52 turtle[48952] INFO:  ImageUtils: setting image functions to alternative sharp implementations
  platform: "android"
  buildPhase: "icons setup"
Jan 6 22:00:52 turtle[48952] INFO:  Resolving universal modules dependencies
  platform: "android"
  buildPhase: "resolve native modules"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo:44.0.0-beta.2
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-application:4.0.1
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-constants:13.0.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-file-system:13.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-font:10.0.4
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-keep-awake:10.0.1
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-modules-core:0.6.2
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-ads-admob:12.0.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-ads-facebook:11.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-analytics-amplitude:11.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-analytics-segment:11.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-app-auth:11.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-apple-authentication:4.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-av:10.2.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-background-fetch:10.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-task-manager:10.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding unimodules-app-loader:3.0.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding unimodules-task-manager-interface:7.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-barcode-scanner:11.2.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-image-loader:3.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-battery:6.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-blur:11.0.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-brightness:10.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-calendar:10.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-camera:12.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-cellular:4.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-clipboard:2.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-contacts:10.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-crypto:10.1.1
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-device:4.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-document-picker:10.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-error-recovery:3.0.4
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-face-detector:11.1.1
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-facebook:12.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-firebase-analytics:6.0.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-firebase-core:4.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-gl:11.1.1
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-gl-cpp:11.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-google-sign-in:10.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-haptics:11.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-image-manipulator:10.2.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-image-picker:12.0.1
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-in-app-purchases:12.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-intent-launcher:10.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-json-utils:0.2.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-linear-gradient:11.0.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-local-authentication:12.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-localization:12.0.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-location:14.0.1
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-mail-composer:11.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-manifests:0.2.2
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-media-library:14.0.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-module-template:10.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-navigation-bar:1.1.1
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-network:4.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-notifications:0.14.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-permissions:13.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-print:11.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-screen-capture:4.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-screen-orientation:4.1.1
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-secure-store:11.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-sensors:11.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-sharing:10.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-sms:10.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-speech:10.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-splash-screen:0.14.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-sqlite:10.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-store-review:5.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-structured-headers:2.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-system-ui:1.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-tracking-transparency:2.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-updates:0.11.1
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-updates-interface:0.5.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-video-thumbnails:6.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Adding expo-web-browser:10.1.0
  platform: "android"
Jan 6 22:00:52 turtle[48952] INFO:  Using manifest: {"android":{"package":"com.iwd","adaptiveIcon":{"backgroundColor":"#FFFFFF"},"permissions":["CAMERA","WRITE_EXTERNAL_STORAGE","READ_EXTERNAL_STORAGE","CAMERA_ROLL"],"versionCode":20},"androidNavigationBar":{"barStyle":"light-content"},"name":"bar","slug":"bar","version":"1.0.0","sdkVersion":"44.0.0","platforms":["ios","android","web"],"currentFullName":"@glabz/bar","originalFullName":"@glabz/bar","locales":{},"bundledAssets":["asset_c00b5b51f0fd354e216f319a78fb252a.png","asset_ae0fcc2b007ded72c6f985671da3338e.png","asset_46d1173c53d96832e868151c1648ea42.png","asset_34d53ae6f3c2303163010aef6efe27ba.png","asset_a610d434605f8a50094a4029a0ea5ff6.png","asset_672c933f8123dda6d0e731c58bd5f4e1.json","asset_6d960622b5d2bdcd2e757ea77d8cd4ea.json","asset_d260a261f41d93b96bdfc1ab7323f29b.json","asset_fb82932703831c5aed5d19b4f66aa1d2.json","asset_9463423d717b1c2a8558909ead75ba09.json","asset_9f05530c64a774d02410e02d0d1554f3.json","asset_2dd3a3e61fb252e9dcb6af9e6aec37ab.json","asset_bcc034acc51c5c8f92c257a28ec9a1d6.json","asset_23bfef5a2cc986befc66df420cb56889.json","asset_2ac32dec71143dccca808a592a85eb9f.json","asset_59e1d07580be5bc3c66af78930b04b98.json","asset_3a2ba31570920eeb9b1d217cabe58315.ttf","asset_8b12b3e16d591abc926165fa8f760e3b.json","asset_744ce60078c17d86006dd0edabcd59a7.ttf","asset_461d9bba8b6a3c91675039df12cfe6ca.json","asset_140c53a7643ea949007aa9a282153849.ttf","asset_94c4ffdcbffeb0570c635d7f8edd8a25.json","asset_e766963327e0a89f9ec2ba88646b6177.ttf","asset_83d0d0700e24da7297be10ae931dd38f.json","asset_b49ae8ab2dbccb02c4d11caaacf09eab.ttf","asset_39843e5d52a6c5c42d5abdb0b34bcaa6.json","asset_b06871f281fee6b241d60582ae9369b9.ttf","asset_f1f91feb805137c9283fb766620ec5eb.json","asset_276ee4e65ded9a91cfe0be813e95e42d.json","asset_8d09f2281ac9c99f438fb1c0b5c66d20.json","asset_db78b9359171f24936b16d84f63af378.ttf","asset_1ab236ed440ee51810c56bd16628aef0.ttf","asset_13685372945d816a2b474fc082fd9aaa.ttf","asset_e20945d7c929279ef7a6f1db184a4470.ttf","asset_60668d999bbaf663420340f7bdd580d7.json","asset_b3263095df30cb7db78c613e73f9499a.ttf","asset_bb0e1479c256e29e7ee92433a5e4b43e.json","asset_6a2ddad1092a0a1c326b6d0e738e682b.ttf","asset_f337aab857fd04843f0a882ec5726fb3.json","asset_8ef52a15e44481b41e7db3c7eaf9bb83.ttf","asset_fdbedb7e67aa7c0ecad83d9c2fa4dfba.json","asset_8e7f807ef943bff1f6d3c2c6e0f3769e.ttf","asset_fdc01171a7a7ea76b187afcd162dee7d.json","asset_d2285965fe34b05465047401b8595dd0.ttf","asset_647543ebfccf6e5495434383598453d1.json","asset_5cdf883b18a5651a29a4d1ef276d2457.ttf","asset_74d124a3caeac2bea111f3ca2f2dd34a.json","asset_a970ccb3cd9a0d56fb2e49159999d02f.json"],"assetUrlOverride":"./assets","publishedTime":"2022-01-06T19:59:37.473Z","commitTime":"2022-01-06T19:59:37.473Z","releaseId":"bbf7fc3b-6289-4992-80cd-1a2a137431bf","revisionId":"mLQVbNkdGd","developer":{"tool":"exp"},"id":"@glabz/bar","platform":"android","bundleUrl":"http://127.0.0.1:8000/bundles/android-78239b2132d26da1beeb77c52b55e10a.js","dependencies":["@expo/vector-icons","@types/styled-components","expo","expo-asset","expo-barcode-scanner","expo-file-system","expo-sqlite","native-base","react","react-dom","react-native","react-native-safe-area-context","react-native-svg","react-native-web","react-redux","react-router-native","redux","simplify-redux-app","styled-components"]}
  platform: "android"
  buildPhase: "reading manifest"

/@expo/xdl@59.1.7/src/detach/AndroidIcons.ts:62
    throw new Error(`Failed to save icon file to disk. (${e})`);
          ^
Error: Failed to save icon file to disk. (TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined)
    at _resizeIconsAsync (/@expo/xdl@59.1.7/src/detach/AndroidIcons.ts:62:11)
    at createAndWriteIconsToPathAsync (/@expo/xdl@59.1.7/src/detach/AndroidIcons.ts:245:3)</pre>
</details>

### Environment

<details>
  <pre> [PUT OUTPUT HERE] </pre>
</details>

**Comment by MagneticaDevelopment** [comment]
same here..
did you find a solution?
it seems it's a JDK problem.

**Comment by fredyonge** [comment]
Same here, could you share if you found a solution

**Comment by MagneticaDevelopment** [comment]
I found the problem!
it's not related to turtle or expo but to the web server (in my case..).
The error was "cannot save icons.." but I also got a 404.
the files in out assets directory don't have the extension so IIS (we use a windows server) wasn't able to serve correctly the file.
adding a jolly handler in the mime type manager solved the problem.
now I have another problem about JDK..
OMG
