### ISSUE TITLE
iOS Builds works on Expo Servers but not on TurtleCLI with the same credentials

### ISSUE THREAD

**Issue by giosuetrapani** [expo/turtle#393]
### New Issue Checklist

- [✅] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [✅] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [✅] I read [docs.expo.dev](https://docs.expo.dev) (Managed Workflow > Distributing Your App).
- [✅] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [✅] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description

Hi everyone,
I'm trying to build the ios archive using turtle-cli on my ci.
It works with `expo build:ios --dist-p12-path <p12> --team-id <id>`
but when i do the same with turtle it fails when copy the mobile provisioning file (the same i have in expo credentials)

##### Command executed

```
expo export --dev --public-url http://localhost:8000
npx http-server -p 8000 -a localhost dist &
sleep 10
curl http://localhost:8000/ios-index.json
sudo turtle setup:ios
sudo turtle build:ios --type "archive" --public-url "http://localhost:8000/ios-index.json" --allow-non-https-public-url --output "./ios_builds/ios.ipa" --team-id <id> --dist-p12-path <p12> --provisioning-profile-path <mobileprovision>
```

##### Complete output when running turtle, including the stack trace and command used

<details>
  <pre> [The directory dist has files that might be overwritten:

  android-index.json
  assets
  bundles
  ios-index.json

Removing existing files from dist
Starting Metro Bundler
[2]    done       sleep 5
iOS Bundling complete 28259ms

Bundle                     Size
┌ index.ios.js          4.39 MB
├ index.android.js      4.38 MB
├ index.ios.js.map      8.74 MB
└ index.android.js.map  8.74 MB

💡 JavaScript bundle sizes affect startup time. Learn more: https://expo.fyi/javascript-bundle-sizes

Finished saving JS Bundles
Analyzing assets
Saving assets
saving /node_modules/react-native/Libraries/LogBox/UI/LogBoxImages/close.png
saving /node_modules/react-native/Libraries/LogBox/UI/LogBoxImages/alert-triangle.png
saving /node_modules/react-native/Libraries/LogBox/UI/LogBoxImages/loader.png
saving /node_modules/react-native/Libraries/LogBox/UI/LogBoxImages/chevron-left.png
saving /node_modules/react-native/Libraries/LogBox/UI/LogBoxImages/chevron-right.png
saving /assets/icon.png
saving /assets/adaptive-icon.png
saving /assets/splash.png
Files successfully saved.

Processing asset bundle patterns:
- /Users/giosuetrapani/Documents/Progetti/Revo/Prova/ProvaFastlane/**/*
Export was successful. Your exported files can be found in dist
[2] 981

Starting up http-server, serving dist

http-server version: 14.1.0

http-server settings: 
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
  http://localhost:8000
Hit CTRL-C to stop the server

[2022-03-17T11:05:47.059Z]  "GET /ios-index.json" "curl/7.77.0"
(node:981) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
{"name":"ProvaFastlane","slug":"ProvaFastlane","version":"2.0.0","orientation":"portrait","icon":"./assets/icon.png","owner":"giosuetrap02","splash":{"image":"./assets/splash.png","resizeMode":"contain","backgroundColor":"#ffffff","imageUrl":"http://localhost:8000/assets/4dc203c1f48ad8b1e9734613e88be661"},"updates":{"fallbackToCacheTimeout":0},"ios":{"supportsTablet":true,"bundleIdentifier":"com.giosuetrap02.Prova","buildNumber":"1"},"android":{"adaptiveIcon":{"foregroundImage":"./assets/adaptive-icon.png","backgroundColor":"#FFFFFF","foregroundImageUrl":"http://localhost:8000/assets/97dae5a0e62ad8551d8a31897b425e63"},"package":"com.giosuetrap02.Prova","versionCode":8,"permissions":["READ_EXTERNAL_STORAGE"]},"web":{"favicon":"./assets/favicon.png"},"sdkVersion":"44.0.0","platforms":["ios","android","web"],"currentFullName":"@giosuetrap02/ProvaFastlane","originalFullName":"@giosuetrap02/ProvaFastlane","locales":{},"iconUrl":"http://localhost:8000/assets/4e3f888fc8475f69fd5fa32f1ad5216a","bundledAssets":["asset_c00b5b51f0fd354e216f319a78fb252a.png","asset_ae0fcc2b007ded72c6f985671da3338e.png","asset_46d1173c53d96832e868151c1648ea42.png","asset_34d53ae6f3c2303163010aef6efe27ba.png","asset_a610d434605f8a50094a4029a0ea5ff6.png"],"assetUrlOverride":"./assets","publishedTime":"2022-03-17T11:05:36.935Z","commitTime":"2022-03-17T11:05:36.935Z","releaseId":"62f94b1a-beb4-42aa-b8de-541a135f9a1c","revisionId":"5Ylwmbkw7y","developer":{"tool":"exp"},"id":"@revogio/ProvaFastlane","platform":"ios","bundleUrl":"http://localhost:8000/bundles/ios-506682240b54d6fdb262287e75653fbc.js","dependencies":["@expo/vector-icons","@react-navigation/bottom-tabs","@react-navigation/native","@react-navigation/native-stack","expo","expo-asset","expo-constants","expo-font","expo-linking","expo-media-library","expo-screen-capture","expo-splash-screen","expo-status-bar","expo-web-browser","react","react-dom","react-native","react-native-responsive-fontsize","react-native-safe-area-context","react-native-screens","react-native-view-shot","react-native-web"]}Mar 17 12:05:58 turtle[992] INFO:  it's all set!
  platform: "ios"
  buildPhase: "setting up environment"
[2022-03-17T11:06:01.773Z]  "GET /ios-index.json" "axios/0.21.1"
Mar 17 12:06:01 turtle[1019] INFO:  Using manifest: {
  "name": "ProvaFastlane",
  "slug": "ProvaFastlane",
  "version": "2.0.0",
  "orientation": "portrait",
  "icon": "./assets/icon.png",
  "owner": "giosuetrap02",
  "splash": {
    "image": "./assets/splash.png",
    "resizeMode": "contain",
    "backgroundColor": "#ffffff",
    "imageUrl": "http://localhost:8000/assets/4dc203c1f48ad8b1e9734613e88be661"
  },
  "updates": {
    "fallbackToCacheTimeout": 0
  },
  "ios": {
    "supportsTablet": true,
    "bundleIdentifier": "com.giosuetrap02.Prova",
    "buildNumber": "1"
  },
  "android": {
    "adaptiveIcon": {
      "foregroundImage": "./assets/adaptive-icon.png",
      "backgroundColor": "#FFFFFF",
      "foregroundImageUrl": "http://localhost:8000/assets/97dae5a0e62ad8551d8a31897b425e63"
    },
    "package": "com.giosuetrap02.Prova",
    "versionCode": 8,
    "permissions": [
      "READ_EXTERNAL_STORAGE"
    ]
  },
  "web": {
    "favicon": "./assets/favicon.png"
  },
  "sdkVersion": "44.0.0",
  "platforms": [
    "ios",
    "android",
    "web"
  ],
  "currentFullName": "@giosuetrap02/ProvaFastlane",
  "originalFullName": "@giosuetrap02/ProvaFastlane",
  "locales": {},
  "iconUrl": "http://localhost:8000/assets/4e3f888fc8475f69fd5fa32f1ad5216a",
  "bundledAssets": [
    "asset_c00b5b51f0fd354e216f319a78fb252a.png",
    "asset_ae0fcc2b007ded72c6f985671da3338e.png",
    "asset_46d1173c53d96832e868151c1648ea42.png",
    "asset_34d53ae6f3c2303163010aef6efe27ba.png",
    "asset_a610d434605f8a50094a4029a0ea5ff6.png"
  ],
  "assetUrlOverride": "./assets",
  "publishedTime": "2022-03-17T11:05:36.935Z",
  "commitTime": "2022-03-17T11:05:36.935Z",
  "releaseId": "62f94b1a-beb4-42aa-b8de-541a135f9a1c",
  "revisionId": "5Ylwmbkw7y",
  "developer": {
    "tool": "exp"
  },
  "id": "@revogio/ProvaFastlane",
  "platform": "ios",
  "bundleUrl": "http://localhost:8000/bundles/ios-506682240b54d6fdb262287e75653fbc.js",
  "dependencies": [
    "@expo/vector-icons",
    "@react-navigation/bottom-tabs",
    "@react-navigation/native",
    "@react-navigation/native-stack",
    "expo",
    "expo-asset",
    "expo-constants",
    "expo-font",
    "expo-linking",
    "expo-media-library",
    "expo-screen-capture",
    "expo-splash-screen",
    "expo-status-bar",
    "expo-web-browser",
    "react",
    "react-dom",
    "react-native",
    "react-native-responsive-fontsize",
    "react-native-safe-area-context",
    "react-native-screens",
    "react-native-view-shot",
    "react-native-web"
  ]
}
  platform: "ios"
  buildPhase: "reading manifest"
Mar 17 12:06:02 turtle[1019] INFO:  creating keychain...
  platform: "ios"
  buildPhase: "creating keychain"
Mar 17 12:06:02 turtle[1019] INFO:  creating new keychain...
  platform: "ios"
  buildPhase: "creating keychain"
Mar 17 12:06:04 turtle[1019] INFO:  Executing command: security show-keychain-info /private/tmp/xdl/3bcf5c40-a5e2-11ec-a7e5-61e93fcdec43.keychain
  platform: "ios"
  buildPhase: "creating keychain"
Mar 17 12:06:04 turtle[1019] INFO:  Keychain "/private/tmp/xdl/3bcf5c40-a5e2-11ec-a7e5-61e93fcdec43.keychain" timeout=360000s
  platform: "ios"
  buildPhase: "creating keychain"
  source: "stdout"
Mar 17 12:06:04 turtle[1019] INFO:  created new keychain
  platform: "ios"
  buildPhase: "creating keychain"
Mar 17 12:06:04 turtle[1019] INFO:  done creating keychain
  platform: "ios"
  buildPhase: "creating keychain"
Mar 17 12:06:04 turtle[1019] INFO:  importing distribution certificate into keychain...
  platform: "ios"
  buildPhase: "importing certificate into keychain"
Mar 17 12:06:04 turtle[1019] INFO:  importing certificate into keychain...
  platform: "ios"
  buildPhase: "importing certificate into keychain"
Mar 17 12:06:04 turtle[1019] INFO:  certificate has password
  platform: "ios"
  buildPhase: "importing certificate into keychain"
Mar 17 12:06:04 turtle[1019] INFO:  1 identity imported.
  platform: "ios"
  buildPhase: "importing certificate into keychain"
  source: "stdout"
Mar 17 12:06:04 turtle[1019] INFO:  imported certificate into keychain
  platform: "ios"
  buildPhase: "importing certificate into keychain"
Mar 17 12:06:04 turtle[1019] INFO:  done importing distribution certificate into keychain
  platform: "ios"
  buildPhase: "importing certificate into keychain"
Mar 17 12:06:05 turtle[1019] INFO:  ImageUtils: setting image functions to alternative sharp implementations
  platform: "ios"
  buildPhase: "icons setup"
Mar 17 12:06:05 turtle[1019] INFO:  configuring NSBundle...
  platform: "ios"
  buildPhase: "configuring NSBundle"
Mar 17 12:06:05 turtle[1019] INFO:  Using manifest: {"name":"ProvaFastlane","slug":"ProvaFastlane","version":"2.0.0","orientation":"portrait","icon":"./assets/icon.png","owner":"giosuetrap02","splash":{"image":"./assets/splash.png","resizeMode":"contain","backgroundColor":"#ffffff","imageUrl":"http://localhost:8000/assets/4dc203c1f48ad8b1e9734613e88be661"},"updates":{"fallbackToCacheTimeout":0},"ios":{"supportsTablet":true,"bundleIdentifier":"com.giosuetrap02.Prova","buildNumber":"1"},"android":{"adaptiveIcon":{"foregroundImage":"./assets/adaptive-icon.png","backgroundColor":"#FFFFFF","foregroundImageUrl":"http://localhost:8000/assets/97dae5a0e62ad8551d8a31897b425e63"},"package":"com.giosuetrap02.Prova","versionCode":8,"permissions":["READ_EXTERNAL_STORAGE"]},"web":{"favicon":"./assets/favicon.png"},"sdkVersion":"44.0.0","platforms":["ios","android","web"],"currentFullName":"@giosuetrap02/ProvaFastlane","originalFullName":"@giosuetrap02/ProvaFastlane","locales":{},"iconUrl":"http://localhost:8000/assets/4e3f888fc8475f69fd5fa32f1ad5216a","bundledAssets":["asset_c00b5b51f0fd354e216f319a78fb252a.png","asset_ae0fcc2b007ded72c6f985671da3338e.png","asset_46d1173c53d96832e868151c1648ea42.png","asset_34d53ae6f3c2303163010aef6efe27ba.png","asset_a610d434605f8a50094a4029a0ea5ff6.png"],"assetUrlOverride":"./assets","publishedTime":"2022-03-17T11:05:36.935Z","commitTime":"2022-03-17T11:05:36.935Z","releaseId":"62f94b1a-beb4-42aa-b8de-541a135f9a1c","revisionId":"5Ylwmbkw7y","developer":{"tool":"exp"},"id":"@revogio/ProvaFastlane","platform":"ios","bundleUrl":"http://localhost:8000/bundles/ios-506682240b54d6fdb262287e75653fbc.js","dependencies":["@expo/vector-icons","@react-navigation/bottom-tabs","@react-navigation/native","@react-navigation/native-stack","expo","expo-asset","expo-constants","expo-font","expo-linking","expo-media-library","expo-screen-capture","expo-splash-screen","expo-status-bar","expo-web-browser","react","react-dom","react-native","react-native-responsive-fontsize","react-native-safe-area-context","react-native-screens","react-native-view-shot","react-native-web"]}
  platform: "ios"
  buildPhase: "reading manifest"
Mar 17 12:06:05 turtle[1019] INFO:  Modifying NSBundle configuration at /private/tmp/turtle/d0777997-0911-4f37-9c2a-c775089ffa8d/archive/Release/ExpoKitApp.xcarchive/Products/Applications/ExpoKitApp.app...
  platform: "ios"
  buildPhase: "configuring NSBundle"
Mar 17 12:06:06 turtle[1019] INFO:  Using standalone config: {
  isShell: true,
  manifestUrl: 'http://localhost:8000/ios-index.json',
  releaseChannel: 'default',
  testEnvironment: 'none',
  updatesFallbackToCacheTimeout: 0
}
  platform: "ios"
  buildPhase: "configuring NSBundle"
Mar 17 12:06:06 turtle[1019] INFO:  Configuring iOS Launch Screen...
  platform: "ios"
  buildPhase: "configuring NSBundle"
[2022-03-17T11:06:06.086Z]  "GET /assets/4dc203c1f48ad8b1e9734613e88be661" "axios/0.21.1"
Mar 17 12:06:10 turtle[1019] INFO:  Bundling assets...
  platform: "ios"
  buildPhase: "configuring NSBundle"
https://classic-assets.eascdn.net/~assets/c00b5b51f0fd354e216f319a78fb252a
https://classic-assets.eascdn.net/~assets/ae0fcc2b007ded72c6f985671da3338e
https://classic-assets.eascdn.net/~assets/46d1173c53d96832e868151c1648ea42
https://classic-assets.eascdn.net/~assets/34d53ae6f3c2303163010aef6efe27ba
https://classic-assets.eascdn.net/~assets/a610d434605f8a50094a4029a0ea5ff6
Mar 17 12:06:11 turtle[1019] INFO:  Compiling resources...
  platform: "ios"
  buildPhase: "configuring NSBundle"
[2022-03-17T11:06:11.164Z]  "GET /assets/4e3f888fc8475f69fd5fa32f1ad5216a" "axios/0.21.1"
2022-03-17 12:06:12.155 ibtoold[1009:9445] DEBUG: Added to environment: {
    TMPDIR = "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/8C669970-D3EE-41A1-AAD1-007BE4E0996F";
}
[2022-03-17T11:06:13.059Z]  "GET /bundles/ios-506682240b54d6fdb262287e75653fbc.js" "axios/0.21.1"
Mar 17 12:06:13 turtle[1019] INFO:  Cleaning up iOS...
  platform: "ios"
  buildPhase: "configuring NSBundle"
Mar 17 12:06:13 turtle[1019] INFO:  building and signing IPA
  platform: "ios"
  buildPhase: "building and signing IPA"
Mar 17 12:06:13 turtle[1019] INFO:  saved provisioning profile to temporary path
  platform: "ios"
  buildPhase: "building and signing IPA"
Mar 17 12:06:13 turtle[1019] INFO:  provisioning profile copied to home directory
  platform: "ios"
  buildPhase: "building and signing IPA"
Mar 17 12:06:13 turtle[1019] INFO:  removed provisioning profile from the home directory
  platform: "ios"
  buildPhase: "building and signing IPA"
Mar 17 12:06:13 turtle[1019] ERROR: Error: security exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/xdl/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at maybeClose (internal/child_process.js:1058:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at Pipe.<anonymous> (net.js:686:12)
    ...
    at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/xdl/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnAsyncThrowError (/@expo/xdl@59.2.0/src/detach/ExponentTools.ts:111:19)
    at readCMSMessage (/@expo/xdl@59.2.0/src/detach/IosIPABuilder.js:118:30)
    at Object.build (/@expo/xdl@59.2.0/src/detach/IosIPABuilder.js:27:31)
    at buildAndSignIPA (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/archive.ts:58:3)
    at Object.buildArchive [as default] (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/archive.ts:20:5)
    at iosBuilder (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/index.ts:33:7)
    at /usr/local/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
    at Command.<anonymous> (/usr/local/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "ios"
Mar 17 12:06:13 turtle[1019] INFO:  delete keychain...
  platform: "ios"
  buildPhase: "deleting keychain"
Mar 17 12:06:13 turtle[1019] INFO:  deleting keychain...
  platform: "ios"
  buildPhase: "deleting keychain"
Mar 17 12:06:15 turtle[1019] INFO:  done deleting keychain
  platform: "ios"
  buildPhase: "deleting keychain"
Mar 17 12:06:15 turtle[1019] ERROR: Failed to build standalone app
  err: Error: security exited with non-zero code: 1
      at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/xdl/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:520:26)
      at ChildProcess.emit (events.js:400:28)
      at ChildProcess.emit (domain.js:475:12)
      at maybeClose (internal/child_process.js:1058:16)
      at Socket.<anonymous> (internal/child_process.js:443:11)
      at Socket.emit (events.js:400:28)
      at Socket.emit (domain.js:475:12)
      at Pipe.<anonymous> (net.js:686:12)
      ...
      at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/xdl/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at spawnAsyncThrowError (/@expo/xdl@59.2.0/src/detach/ExponentTools.ts:111:19)
      at readCMSMessage (/@expo/xdl@59.2.0/src/detach/IosIPABuilder.js:118:30)
      at Object.build (/@expo/xdl@59.2.0/src/detach/IosIPABuilder.js:27:31)
      at buildAndSignIPA (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/archive.ts:58:3)
      at Object.buildArchive [as default] (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/archive.ts:20:5)
      at iosBuilder (/usr/local/lib/node_modules/turtle-cli/src/builders/ios/index.ts:33:7)
      at /usr/local/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
      at Command.<anonymous> (/usr/local/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "ios"]</pre>
</details>

### Environment

<details>
  <pre>[Expo CLI 5.2.0 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.16 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: Bumblebee 2021.1.1 Patch 2 Bumblebee 2021.1.1 Patch 2
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.2.0
    Expo Workflow: managed]</pre>
</details>

**Comment by giosuetrapani** [comment]
Find out `security` have problem using sudo, trying to do all without sudo changing folder permissions
